#!/bin/bash
# Copyright 2021 OpenHW Group
# Solderpad Hardware License, Version 2.1, see LICENSE.md for details.
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1

find hw/mage/access hw/mage/configuration hw/mage/xbars hw/mage/execute hw/mage/execute/pe hw/mage/execute/pe/fu hw/mage/execute/pe/fu/div hw/mage/packages hw/mage/memory hw/mage/stream tb -name '*.sv*' | xargs verible-verilog-format --inplace 2> /dev/zero
