// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package mage_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 9;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_pe_00_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_pe_01_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_pe_02_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_pe_03_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_pe_10_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_pe_11_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_pe_12_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_pe_13_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_pe_20_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_pe_21_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_pe_22_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_pe_23_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_pe_30_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_pe_31_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_pe_32_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_pe_33_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_pea_constants_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_pea_rf_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_trans_size_dma_ch_0_reg_t;

  typedef struct packed {logic [15:0] q;} mage_reg2hw_trans_size_sync_dma_ch_0_reg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_trans_size_dma_ch_1_reg_t;

  typedef struct packed {logic [15:0] q;} mage_reg2hw_trans_size_sync_dma_ch_1_reg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_trans_size_dma_ch_2_reg_t;

  typedef struct packed {logic [15:0] q;} mage_reg2hw_trans_size_sync_dma_ch_2_reg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_trans_size_dma_ch_3_reg_t;

  typedef struct packed {logic [15:0] q;} mage_reg2hw_trans_size_sync_dma_ch_3_reg_t;

  typedef struct packed {logic [3:0] q;} mage_reg2hw_dma_rnw_reg_t;

  typedef struct packed {logic [1:0] q;} mage_reg2hw_cols_grouping_reg_t;

  typedef struct packed {logic q;} mage_reg2hw_sync_dma_ch_reg_t;

  typedef struct packed {logic [3:0] q;} mage_reg2hw_sync_dma_ch_trans_reg_t;

  typedef struct packed {
    struct packed {logic [1:0] q;} sel_out_xbar_0;
    struct packed {logic [1:0] q;} sel_out_xbar_1;
    struct packed {logic [1:0] q;} sel_out_xbar_2;
    struct packed {logic [1:0] q;} sel_out_xbar_3;
  } mage_reg2hw_stream_out_xbar_sel_reg_t;

  typedef struct packed {
    struct packed {logic [3:0] q;} sel_col_0;
    struct packed {logic [3:0] q;} sel_col_1;
    struct packed {logic [3:0] q;} sel_col_2;
    struct packed {logic [3:0] q;} sel_col_3;
  } mage_reg2hw_sel_out_col_pea_mreg_t;

  typedef struct packed {logic [15:0] q;} mage_reg2hw_acc_value_mreg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } mage_hw2reg_pea_rf_mreg_t;

  // Register -> HW type
  typedef struct packed {
    mage_reg2hw_cfg_pe_00_mreg_t [0:0] cfg_pe_00;  // [2018:1987]
    mage_reg2hw_cfg_pe_01_mreg_t [0:0] cfg_pe_01;  // [1986:1955]
    mage_reg2hw_cfg_pe_02_mreg_t [0:0] cfg_pe_02;  // [1954:1923]
    mage_reg2hw_cfg_pe_03_mreg_t [0:0] cfg_pe_03;  // [1922:1891]
    mage_reg2hw_cfg_pe_10_mreg_t [0:0] cfg_pe_10;  // [1890:1859]
    mage_reg2hw_cfg_pe_11_mreg_t [0:0] cfg_pe_11;  // [1858:1827]
    mage_reg2hw_cfg_pe_12_mreg_t [0:0] cfg_pe_12;  // [1826:1795]
    mage_reg2hw_cfg_pe_13_mreg_t [0:0] cfg_pe_13;  // [1794:1763]
    mage_reg2hw_cfg_pe_20_mreg_t [0:0] cfg_pe_20;  // [1762:1731]
    mage_reg2hw_cfg_pe_21_mreg_t [0:0] cfg_pe_21;  // [1730:1699]
    mage_reg2hw_cfg_pe_22_mreg_t [0:0] cfg_pe_22;  // [1698:1667]
    mage_reg2hw_cfg_pe_23_mreg_t [0:0] cfg_pe_23;  // [1666:1635]
    mage_reg2hw_cfg_pe_30_mreg_t [0:0] cfg_pe_30;  // [1634:1603]
    mage_reg2hw_cfg_pe_31_mreg_t [0:0] cfg_pe_31;  // [1602:1571]
    mage_reg2hw_cfg_pe_32_mreg_t [0:0] cfg_pe_32;  // [1570:1539]
    mage_reg2hw_cfg_pe_33_mreg_t [0:0] cfg_pe_33;  // [1538:1507]
    mage_reg2hw_pea_constants_mreg_t [15:0] pea_constants;  // [1506:995]
    mage_reg2hw_pea_rf_mreg_t [15:0] pea_rf;  // [994:483]
    mage_reg2hw_trans_size_dma_ch_0_reg_t trans_size_dma_ch_0;  // [482:451]
    mage_reg2hw_trans_size_sync_dma_ch_0_reg_t trans_size_sync_dma_ch_0;  // [450:435]
    mage_reg2hw_trans_size_dma_ch_1_reg_t trans_size_dma_ch_1;  // [434:403]
    mage_reg2hw_trans_size_sync_dma_ch_1_reg_t trans_size_sync_dma_ch_1;  // [402:387]
    mage_reg2hw_trans_size_dma_ch_2_reg_t trans_size_dma_ch_2;  // [386:355]
    mage_reg2hw_trans_size_sync_dma_ch_2_reg_t trans_size_sync_dma_ch_2;  // [354:339]
    mage_reg2hw_trans_size_dma_ch_3_reg_t trans_size_dma_ch_3;  // [338:307]
    mage_reg2hw_trans_size_sync_dma_ch_3_reg_t trans_size_sync_dma_ch_3;  // [306:291]
    mage_reg2hw_dma_rnw_reg_t dma_rnw;  // [290:287]
    mage_reg2hw_cols_grouping_reg_t cols_grouping;  // [286:285]
    mage_reg2hw_sync_dma_ch_reg_t sync_dma_ch;  // [284:284]
    mage_reg2hw_sync_dma_ch_trans_reg_t sync_dma_ch_trans;  // [283:280]
    mage_reg2hw_stream_out_xbar_sel_reg_t stream_out_xbar_sel;  // [279:272]
    mage_reg2hw_sel_out_col_pea_mreg_t [0:0] sel_out_col_pea;  // [271:256]
    mage_reg2hw_acc_value_mreg_t [15:0] acc_value;  // [255:0]
  } mage_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    mage_hw2reg_pea_rf_mreg_t [15:0] pea_rf;  // [527:0]
  } mage_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] MAGE_CFG_PE_00_OFFSET = 9'h0;
  parameter logic [BlockAw-1:0] MAGE_CFG_PE_01_OFFSET = 9'h4;
  parameter logic [BlockAw-1:0] MAGE_CFG_PE_02_OFFSET = 9'h8;
  parameter logic [BlockAw-1:0] MAGE_CFG_PE_03_OFFSET = 9'hc;
  parameter logic [BlockAw-1:0] MAGE_CFG_PE_10_OFFSET = 9'h10;
  parameter logic [BlockAw-1:0] MAGE_CFG_PE_11_OFFSET = 9'h14;
  parameter logic [BlockAw-1:0] MAGE_CFG_PE_12_OFFSET = 9'h18;
  parameter logic [BlockAw-1:0] MAGE_CFG_PE_13_OFFSET = 9'h1c;
  parameter logic [BlockAw-1:0] MAGE_CFG_PE_20_OFFSET = 9'h20;
  parameter logic [BlockAw-1:0] MAGE_CFG_PE_21_OFFSET = 9'h24;
  parameter logic [BlockAw-1:0] MAGE_CFG_PE_22_OFFSET = 9'h28;
  parameter logic [BlockAw-1:0] MAGE_CFG_PE_23_OFFSET = 9'h2c;
  parameter logic [BlockAw-1:0] MAGE_CFG_PE_30_OFFSET = 9'h30;
  parameter logic [BlockAw-1:0] MAGE_CFG_PE_31_OFFSET = 9'h34;
  parameter logic [BlockAw-1:0] MAGE_CFG_PE_32_OFFSET = 9'h38;
  parameter logic [BlockAw-1:0] MAGE_CFG_PE_33_OFFSET = 9'h3c;
  parameter logic [BlockAw-1:0] MAGE_PEA_CONSTANTS_0_OFFSET = 9'h40;
  parameter logic [BlockAw-1:0] MAGE_PEA_CONSTANTS_1_OFFSET = 9'h44;
  parameter logic [BlockAw-1:0] MAGE_PEA_CONSTANTS_2_OFFSET = 9'h48;
  parameter logic [BlockAw-1:0] MAGE_PEA_CONSTANTS_3_OFFSET = 9'h4c;
  parameter logic [BlockAw-1:0] MAGE_PEA_CONSTANTS_4_OFFSET = 9'h50;
  parameter logic [BlockAw-1:0] MAGE_PEA_CONSTANTS_5_OFFSET = 9'h54;
  parameter logic [BlockAw-1:0] MAGE_PEA_CONSTANTS_6_OFFSET = 9'h58;
  parameter logic [BlockAw-1:0] MAGE_PEA_CONSTANTS_7_OFFSET = 9'h5c;
  parameter logic [BlockAw-1:0] MAGE_PEA_CONSTANTS_8_OFFSET = 9'h60;
  parameter logic [BlockAw-1:0] MAGE_PEA_CONSTANTS_9_OFFSET = 9'h64;
  parameter logic [BlockAw-1:0] MAGE_PEA_CONSTANTS_10_OFFSET = 9'h68;
  parameter logic [BlockAw-1:0] MAGE_PEA_CONSTANTS_11_OFFSET = 9'h6c;
  parameter logic [BlockAw-1:0] MAGE_PEA_CONSTANTS_12_OFFSET = 9'h70;
  parameter logic [BlockAw-1:0] MAGE_PEA_CONSTANTS_13_OFFSET = 9'h74;
  parameter logic [BlockAw-1:0] MAGE_PEA_CONSTANTS_14_OFFSET = 9'h78;
  parameter logic [BlockAw-1:0] MAGE_PEA_CONSTANTS_15_OFFSET = 9'h7c;
  parameter logic [BlockAw-1:0] MAGE_PEA_RF_0_OFFSET = 9'h80;
  parameter logic [BlockAw-1:0] MAGE_PEA_RF_1_OFFSET = 9'h84;
  parameter logic [BlockAw-1:0] MAGE_PEA_RF_2_OFFSET = 9'h88;
  parameter logic [BlockAw-1:0] MAGE_PEA_RF_3_OFFSET = 9'h8c;
  parameter logic [BlockAw-1:0] MAGE_PEA_RF_4_OFFSET = 9'h90;
  parameter logic [BlockAw-1:0] MAGE_PEA_RF_5_OFFSET = 9'h94;
  parameter logic [BlockAw-1:0] MAGE_PEA_RF_6_OFFSET = 9'h98;
  parameter logic [BlockAw-1:0] MAGE_PEA_RF_7_OFFSET = 9'h9c;
  parameter logic [BlockAw-1:0] MAGE_PEA_RF_8_OFFSET = 9'ha0;
  parameter logic [BlockAw-1:0] MAGE_PEA_RF_9_OFFSET = 9'ha4;
  parameter logic [BlockAw-1:0] MAGE_PEA_RF_10_OFFSET = 9'ha8;
  parameter logic [BlockAw-1:0] MAGE_PEA_RF_11_OFFSET = 9'hac;
  parameter logic [BlockAw-1:0] MAGE_PEA_RF_12_OFFSET = 9'hb0;
  parameter logic [BlockAw-1:0] MAGE_PEA_RF_13_OFFSET = 9'hb4;
  parameter logic [BlockAw-1:0] MAGE_PEA_RF_14_OFFSET = 9'hb8;
  parameter logic [BlockAw-1:0] MAGE_PEA_RF_15_OFFSET = 9'hbc;
  parameter logic [BlockAw-1:0] MAGE_TRANS_SIZE_DMA_CH_0_OFFSET = 9'hc0;
  parameter logic [BlockAw-1:0] MAGE_TRANS_SIZE_SYNC_DMA_CH_0_OFFSET = 9'hc4;
  parameter logic [BlockAw-1:0] MAGE_TRANS_SIZE_DMA_CH_1_OFFSET = 9'hc8;
  parameter logic [BlockAw-1:0] MAGE_TRANS_SIZE_SYNC_DMA_CH_1_OFFSET = 9'hcc;
  parameter logic [BlockAw-1:0] MAGE_TRANS_SIZE_DMA_CH_2_OFFSET = 9'hd0;
  parameter logic [BlockAw-1:0] MAGE_TRANS_SIZE_SYNC_DMA_CH_2_OFFSET = 9'hd4;
  parameter logic [BlockAw-1:0] MAGE_TRANS_SIZE_DMA_CH_3_OFFSET = 9'hd8;
  parameter logic [BlockAw-1:0] MAGE_TRANS_SIZE_SYNC_DMA_CH_3_OFFSET = 9'hdc;
  parameter logic [BlockAw-1:0] MAGE_DMA_RNW_OFFSET = 9'he0;
  parameter logic [BlockAw-1:0] MAGE_COLS_GROUPING_OFFSET = 9'he4;
  parameter logic [BlockAw-1:0] MAGE_SYNC_DMA_CH_OFFSET = 9'he8;
  parameter logic [BlockAw-1:0] MAGE_SYNC_DMA_CH_TRANS_OFFSET = 9'hec;
  parameter logic [BlockAw-1:0] MAGE_STREAM_OUT_XBAR_SEL_OFFSET = 9'hf0;
  parameter logic [BlockAw-1:0] MAGE_SEL_OUT_COL_PEA_OFFSET = 9'hf4;
  parameter logic [BlockAw-1:0] MAGE_ACC_VALUE_0_OFFSET = 9'hf8;
  parameter logic [BlockAw-1:0] MAGE_ACC_VALUE_1_OFFSET = 9'hfc;
  parameter logic [BlockAw-1:0] MAGE_ACC_VALUE_2_OFFSET = 9'h100;
  parameter logic [BlockAw-1:0] MAGE_ACC_VALUE_3_OFFSET = 9'h104;
  parameter logic [BlockAw-1:0] MAGE_ACC_VALUE_4_OFFSET = 9'h108;
  parameter logic [BlockAw-1:0] MAGE_ACC_VALUE_5_OFFSET = 9'h10c;
  parameter logic [BlockAw-1:0] MAGE_ACC_VALUE_6_OFFSET = 9'h110;
  parameter logic [BlockAw-1:0] MAGE_ACC_VALUE_7_OFFSET = 9'h114;

  // Register index
  typedef enum int {
    MAGE_CFG_PE_00,
    MAGE_CFG_PE_01,
    MAGE_CFG_PE_02,
    MAGE_CFG_PE_03,
    MAGE_CFG_PE_10,
    MAGE_CFG_PE_11,
    MAGE_CFG_PE_12,
    MAGE_CFG_PE_13,
    MAGE_CFG_PE_20,
    MAGE_CFG_PE_21,
    MAGE_CFG_PE_22,
    MAGE_CFG_PE_23,
    MAGE_CFG_PE_30,
    MAGE_CFG_PE_31,
    MAGE_CFG_PE_32,
    MAGE_CFG_PE_33,
    MAGE_PEA_CONSTANTS_0,
    MAGE_PEA_CONSTANTS_1,
    MAGE_PEA_CONSTANTS_2,
    MAGE_PEA_CONSTANTS_3,
    MAGE_PEA_CONSTANTS_4,
    MAGE_PEA_CONSTANTS_5,
    MAGE_PEA_CONSTANTS_6,
    MAGE_PEA_CONSTANTS_7,
    MAGE_PEA_CONSTANTS_8,
    MAGE_PEA_CONSTANTS_9,
    MAGE_PEA_CONSTANTS_10,
    MAGE_PEA_CONSTANTS_11,
    MAGE_PEA_CONSTANTS_12,
    MAGE_PEA_CONSTANTS_13,
    MAGE_PEA_CONSTANTS_14,
    MAGE_PEA_CONSTANTS_15,
    MAGE_PEA_RF_0,
    MAGE_PEA_RF_1,
    MAGE_PEA_RF_2,
    MAGE_PEA_RF_3,
    MAGE_PEA_RF_4,
    MAGE_PEA_RF_5,
    MAGE_PEA_RF_6,
    MAGE_PEA_RF_7,
    MAGE_PEA_RF_8,
    MAGE_PEA_RF_9,
    MAGE_PEA_RF_10,
    MAGE_PEA_RF_11,
    MAGE_PEA_RF_12,
    MAGE_PEA_RF_13,
    MAGE_PEA_RF_14,
    MAGE_PEA_RF_15,
    MAGE_TRANS_SIZE_DMA_CH_0,
    MAGE_TRANS_SIZE_SYNC_DMA_CH_0,
    MAGE_TRANS_SIZE_DMA_CH_1,
    MAGE_TRANS_SIZE_SYNC_DMA_CH_1,
    MAGE_TRANS_SIZE_DMA_CH_2,
    MAGE_TRANS_SIZE_SYNC_DMA_CH_2,
    MAGE_TRANS_SIZE_DMA_CH_3,
    MAGE_TRANS_SIZE_SYNC_DMA_CH_3,
    MAGE_DMA_RNW,
    MAGE_COLS_GROUPING,
    MAGE_SYNC_DMA_CH,
    MAGE_SYNC_DMA_CH_TRANS,
    MAGE_STREAM_OUT_XBAR_SEL,
    MAGE_SEL_OUT_COL_PEA,
    MAGE_ACC_VALUE_0,
    MAGE_ACC_VALUE_1,
    MAGE_ACC_VALUE_2,
    MAGE_ACC_VALUE_3,
    MAGE_ACC_VALUE_4,
    MAGE_ACC_VALUE_5,
    MAGE_ACC_VALUE_6,
    MAGE_ACC_VALUE_7
  } mage_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] MAGE_PERMIT[70] = '{
      4'b1111,  // index[ 0] MAGE_CFG_PE_00
      4'b1111,  // index[ 1] MAGE_CFG_PE_01
      4'b1111,  // index[ 2] MAGE_CFG_PE_02
      4'b1111,  // index[ 3] MAGE_CFG_PE_03
      4'b1111,  // index[ 4] MAGE_CFG_PE_10
      4'b1111,  // index[ 5] MAGE_CFG_PE_11
      4'b1111,  // index[ 6] MAGE_CFG_PE_12
      4'b1111,  // index[ 7] MAGE_CFG_PE_13
      4'b1111,  // index[ 8] MAGE_CFG_PE_20
      4'b1111,  // index[ 9] MAGE_CFG_PE_21
      4'b1111,  // index[10] MAGE_CFG_PE_22
      4'b1111,  // index[11] MAGE_CFG_PE_23
      4'b1111,  // index[12] MAGE_CFG_PE_30
      4'b1111,  // index[13] MAGE_CFG_PE_31
      4'b1111,  // index[14] MAGE_CFG_PE_32
      4'b1111,  // index[15] MAGE_CFG_PE_33
      4'b1111,  // index[16] MAGE_PEA_CONSTANTS_0
      4'b1111,  // index[17] MAGE_PEA_CONSTANTS_1
      4'b1111,  // index[18] MAGE_PEA_CONSTANTS_2
      4'b1111,  // index[19] MAGE_PEA_CONSTANTS_3
      4'b1111,  // index[20] MAGE_PEA_CONSTANTS_4
      4'b1111,  // index[21] MAGE_PEA_CONSTANTS_5
      4'b1111,  // index[22] MAGE_PEA_CONSTANTS_6
      4'b1111,  // index[23] MAGE_PEA_CONSTANTS_7
      4'b1111,  // index[24] MAGE_PEA_CONSTANTS_8
      4'b1111,  // index[25] MAGE_PEA_CONSTANTS_9
      4'b1111,  // index[26] MAGE_PEA_CONSTANTS_10
      4'b1111,  // index[27] MAGE_PEA_CONSTANTS_11
      4'b1111,  // index[28] MAGE_PEA_CONSTANTS_12
      4'b1111,  // index[29] MAGE_PEA_CONSTANTS_13
      4'b1111,  // index[30] MAGE_PEA_CONSTANTS_14
      4'b1111,  // index[31] MAGE_PEA_CONSTANTS_15
      4'b1111,  // index[32] MAGE_PEA_RF_0
      4'b1111,  // index[33] MAGE_PEA_RF_1
      4'b1111,  // index[34] MAGE_PEA_RF_2
      4'b1111,  // index[35] MAGE_PEA_RF_3
      4'b1111,  // index[36] MAGE_PEA_RF_4
      4'b1111,  // index[37] MAGE_PEA_RF_5
      4'b1111,  // index[38] MAGE_PEA_RF_6
      4'b1111,  // index[39] MAGE_PEA_RF_7
      4'b1111,  // index[40] MAGE_PEA_RF_8
      4'b1111,  // index[41] MAGE_PEA_RF_9
      4'b1111,  // index[42] MAGE_PEA_RF_10
      4'b1111,  // index[43] MAGE_PEA_RF_11
      4'b1111,  // index[44] MAGE_PEA_RF_12
      4'b1111,  // index[45] MAGE_PEA_RF_13
      4'b1111,  // index[46] MAGE_PEA_RF_14
      4'b1111,  // index[47] MAGE_PEA_RF_15
      4'b1111,  // index[48] MAGE_TRANS_SIZE_DMA_CH_0
      4'b0011,  // index[49] MAGE_TRANS_SIZE_SYNC_DMA_CH_0
      4'b1111,  // index[50] MAGE_TRANS_SIZE_DMA_CH_1
      4'b0011,  // index[51] MAGE_TRANS_SIZE_SYNC_DMA_CH_1
      4'b1111,  // index[52] MAGE_TRANS_SIZE_DMA_CH_2
      4'b0011,  // index[53] MAGE_TRANS_SIZE_SYNC_DMA_CH_2
      4'b1111,  // index[54] MAGE_TRANS_SIZE_DMA_CH_3
      4'b0011,  // index[55] MAGE_TRANS_SIZE_SYNC_DMA_CH_3
      4'b0001,  // index[56] MAGE_DMA_RNW
      4'b0001,  // index[57] MAGE_COLS_GROUPING
      4'b0001,  // index[58] MAGE_SYNC_DMA_CH
      4'b0001,  // index[59] MAGE_SYNC_DMA_CH_TRANS
      4'b0001,  // index[60] MAGE_STREAM_OUT_XBAR_SEL
      4'b0011,  // index[61] MAGE_SEL_OUT_COL_PEA
      4'b1111,  // index[62] MAGE_ACC_VALUE_0
      4'b1111,  // index[63] MAGE_ACC_VALUE_1
      4'b1111,  // index[64] MAGE_ACC_VALUE_2
      4'b1111,  // index[65] MAGE_ACC_VALUE_3
      4'b1111,  // index[66] MAGE_ACC_VALUE_4
      4'b1111,  // index[67] MAGE_ACC_VALUE_5
      4'b1111,  // index[68] MAGE_ACC_VALUE_6
      4'b1111  // index[69] MAGE_ACC_VALUE_7
  };

endpackage

