// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module mage_reg_top #(
    parameter type reg_req_t = logic,
    parameter type reg_rsp_t = logic,
    parameter int AW = 8
) (
    input logic clk_i,
    input logic rst_ni,
    input reg_req_t reg_req_i,
    output reg_rsp_t reg_rsp_o,
    // To HW
    output mage_reg_pkg::mage_reg2hw_t reg2hw,  // Write


    // Config
    input devmode_i  // If 1, explicit error return for unmapped register access
);

  import mage_reg_pkg::*;

  localparam int DW = 32;
  localparam int DBW = DW / 8;  // Byte Width

  // register signals
  logic               reg_we;
  logic               reg_re;
  logic [BlockAw-1:0] reg_addr;
  logic [     DW-1:0] reg_wdata;
  logic [    DBW-1:0] reg_be;
  logic [     DW-1:0] reg_rdata;
  logic               reg_error;

  logic addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t reg_intf_req;
  reg_rsp_t reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr[BlockAw-1:0];
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic [31:0] cfg_pe_00_qs;
  logic [31:0] cfg_pe_00_wd;
  logic cfg_pe_00_we;
  logic [31:0] cfg_pe_01_qs;
  logic [31:0] cfg_pe_01_wd;
  logic cfg_pe_01_we;
  logic [31:0] cfg_pe_02_qs;
  logic [31:0] cfg_pe_02_wd;
  logic cfg_pe_02_we;
  logic [31:0] cfg_pe_03_qs;
  logic [31:0] cfg_pe_03_wd;
  logic cfg_pe_03_we;
  logic [31:0] cfg_pe_10_qs;
  logic [31:0] cfg_pe_10_wd;
  logic cfg_pe_10_we;
  logic [31:0] cfg_pe_11_qs;
  logic [31:0] cfg_pe_11_wd;
  logic cfg_pe_11_we;
  logic [31:0] cfg_pe_12_qs;
  logic [31:0] cfg_pe_12_wd;
  logic cfg_pe_12_we;
  logic [31:0] cfg_pe_13_qs;
  logic [31:0] cfg_pe_13_wd;
  logic cfg_pe_13_we;
  logic [31:0] cfg_pe_20_qs;
  logic [31:0] cfg_pe_20_wd;
  logic cfg_pe_20_we;
  logic [31:0] cfg_pe_21_qs;
  logic [31:0] cfg_pe_21_wd;
  logic cfg_pe_21_we;
  logic [31:0] cfg_pe_22_qs;
  logic [31:0] cfg_pe_22_wd;
  logic cfg_pe_22_we;
  logic [31:0] cfg_pe_23_qs;
  logic [31:0] cfg_pe_23_wd;
  logic cfg_pe_23_we;
  logic [31:0] cfg_pe_30_qs;
  logic [31:0] cfg_pe_30_wd;
  logic cfg_pe_30_we;
  logic [31:0] cfg_pe_31_qs;
  logic [31:0] cfg_pe_31_wd;
  logic cfg_pe_31_we;
  logic [31:0] cfg_pe_32_qs;
  logic [31:0] cfg_pe_32_wd;
  logic cfg_pe_32_we;
  logic [31:0] cfg_pe_33_qs;
  logic [31:0] cfg_pe_33_wd;
  logic cfg_pe_33_we;
  logic [31:0] pea_constants_0_qs;
  logic [31:0] pea_constants_0_wd;
  logic pea_constants_0_we;
  logic [31:0] pea_constants_1_qs;
  logic [31:0] pea_constants_1_wd;
  logic pea_constants_1_we;
  logic [31:0] pea_constants_2_qs;
  logic [31:0] pea_constants_2_wd;
  logic pea_constants_2_we;
  logic [31:0] pea_constants_3_qs;
  logic [31:0] pea_constants_3_wd;
  logic pea_constants_3_we;
  logic [31:0] pea_constants_4_qs;
  logic [31:0] pea_constants_4_wd;
  logic pea_constants_4_we;
  logic [31:0] pea_constants_5_qs;
  logic [31:0] pea_constants_5_wd;
  logic pea_constants_5_we;
  logic [31:0] pea_constants_6_qs;
  logic [31:0] pea_constants_6_wd;
  logic pea_constants_6_we;
  logic [31:0] pea_constants_7_qs;
  logic [31:0] pea_constants_7_wd;
  logic pea_constants_7_we;
  logic [31:0] pea_constants_8_qs;
  logic [31:0] pea_constants_8_wd;
  logic pea_constants_8_we;
  logic [31:0] pea_constants_9_qs;
  logic [31:0] pea_constants_9_wd;
  logic pea_constants_9_we;
  logic [31:0] pea_constants_10_qs;
  logic [31:0] pea_constants_10_wd;
  logic pea_constants_10_we;
  logic [31:0] pea_constants_11_qs;
  logic [31:0] pea_constants_11_wd;
  logic pea_constants_11_we;
  logic [31:0] pea_constants_12_qs;
  logic [31:0] pea_constants_12_wd;
  logic pea_constants_12_we;
  logic [31:0] pea_constants_13_qs;
  logic [31:0] pea_constants_13_wd;
  logic pea_constants_13_we;
  logic [31:0] pea_constants_14_qs;
  logic [31:0] pea_constants_14_wd;
  logic pea_constants_14_we;
  logic [31:0] pea_constants_15_qs;
  logic [31:0] pea_constants_15_wd;
  logic pea_constants_15_we;
  logic [3:0] stream_dma_cfg_qs;
  logic [3:0] stream_dma_cfg_wd;
  logic stream_dma_cfg_we;
  logic [1:0] separate_cols_qs;
  logic [1:0] separate_cols_wd;
  logic separate_cols_we;
  logic [7:0] sel_out_col_pea_sel_col_0_0_qs;
  logic [7:0] sel_out_col_pea_sel_col_0_0_wd;
  logic sel_out_col_pea_sel_col_0_0_we;
  logic [7:0] sel_out_col_pea_sel_col_1_0_qs;
  logic [7:0] sel_out_col_pea_sel_col_1_0_wd;
  logic sel_out_col_pea_sel_col_1_0_we;
  logic [7:0] sel_out_col_pea_sel_col_2_0_qs;
  logic [7:0] sel_out_col_pea_sel_col_2_0_wd;
  logic sel_out_col_pea_sel_col_2_0_we;
  logic [7:0] sel_out_col_pea_sel_col_3_0_qs;
  logic [7:0] sel_out_col_pea_sel_col_3_0_wd;
  logic sel_out_col_pea_sel_col_3_0_we;
  logic [31:0] acc_value_0_qs;
  logic [31:0] acc_value_0_wd;
  logic acc_value_0_we;
  logic [31:0] acc_value_1_qs;
  logic [31:0] acc_value_1_wd;
  logic acc_value_1_we;
  logic [31:0] acc_value_2_qs;
  logic [31:0] acc_value_2_wd;
  logic acc_value_2_we;
  logic [31:0] acc_value_3_qs;
  logic [31:0] acc_value_3_wd;
  logic acc_value_3_we;
  logic [31:0] acc_value_4_qs;
  logic [31:0] acc_value_4_wd;
  logic acc_value_4_we;
  logic [31:0] acc_value_5_qs;
  logic [31:0] acc_value_5_wd;
  logic acc_value_5_we;
  logic [31:0] acc_value_6_qs;
  logic [31:0] acc_value_6_wd;
  logic acc_value_6_we;
  logic [31:0] acc_value_7_qs;
  logic [31:0] acc_value_7_wd;
  logic acc_value_7_we;
  logic [31:0] acc_value_8_qs;
  logic [31:0] acc_value_8_wd;
  logic acc_value_8_we;
  logic [31:0] acc_value_9_qs;
  logic [31:0] acc_value_9_wd;
  logic acc_value_9_we;
  logic [31:0] acc_value_10_qs;
  logic [31:0] acc_value_10_wd;
  logic acc_value_10_we;
  logic [31:0] acc_value_11_qs;
  logic [31:0] acc_value_11_wd;
  logic acc_value_11_we;
  logic [31:0] acc_value_12_qs;
  logic [31:0] acc_value_12_wd;
  logic acc_value_12_we;
  logic [31:0] acc_value_13_qs;
  logic [31:0] acc_value_13_wd;
  logic acc_value_13_we;
  logic [31:0] acc_value_14_qs;
  logic [31:0] acc_value_14_wd;
  logic acc_value_14_we;
  logic [31:0] acc_value_15_qs;
  logic [31:0] acc_value_15_wd;
  logic acc_value_15_we;

  // Register instances

  // Subregister 0 of Multireg cfg_pe_00
  // R[cfg_pe_00]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_cfg_pe_00 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(cfg_pe_00_we),
      .wd(cfg_pe_00_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.cfg_pe_00[0].q),

      // to register interface (read)
      .qs(cfg_pe_00_qs)
  );



  // Subregister 0 of Multireg cfg_pe_01
  // R[cfg_pe_01]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_cfg_pe_01 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(cfg_pe_01_we),
      .wd(cfg_pe_01_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.cfg_pe_01[0].q),

      // to register interface (read)
      .qs(cfg_pe_01_qs)
  );



  // Subregister 0 of Multireg cfg_pe_02
  // R[cfg_pe_02]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_cfg_pe_02 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(cfg_pe_02_we),
      .wd(cfg_pe_02_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.cfg_pe_02[0].q),

      // to register interface (read)
      .qs(cfg_pe_02_qs)
  );



  // Subregister 0 of Multireg cfg_pe_03
  // R[cfg_pe_03]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_cfg_pe_03 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(cfg_pe_03_we),
      .wd(cfg_pe_03_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.cfg_pe_03[0].q),

      // to register interface (read)
      .qs(cfg_pe_03_qs)
  );



  // Subregister 0 of Multireg cfg_pe_10
  // R[cfg_pe_10]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_cfg_pe_10 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(cfg_pe_10_we),
      .wd(cfg_pe_10_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.cfg_pe_10[0].q),

      // to register interface (read)
      .qs(cfg_pe_10_qs)
  );



  // Subregister 0 of Multireg cfg_pe_11
  // R[cfg_pe_11]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_cfg_pe_11 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(cfg_pe_11_we),
      .wd(cfg_pe_11_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.cfg_pe_11[0].q),

      // to register interface (read)
      .qs(cfg_pe_11_qs)
  );



  // Subregister 0 of Multireg cfg_pe_12
  // R[cfg_pe_12]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_cfg_pe_12 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(cfg_pe_12_we),
      .wd(cfg_pe_12_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.cfg_pe_12[0].q),

      // to register interface (read)
      .qs(cfg_pe_12_qs)
  );



  // Subregister 0 of Multireg cfg_pe_13
  // R[cfg_pe_13]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_cfg_pe_13 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(cfg_pe_13_we),
      .wd(cfg_pe_13_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.cfg_pe_13[0].q),

      // to register interface (read)
      .qs(cfg_pe_13_qs)
  );



  // Subregister 0 of Multireg cfg_pe_20
  // R[cfg_pe_20]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_cfg_pe_20 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(cfg_pe_20_we),
      .wd(cfg_pe_20_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.cfg_pe_20[0].q),

      // to register interface (read)
      .qs(cfg_pe_20_qs)
  );



  // Subregister 0 of Multireg cfg_pe_21
  // R[cfg_pe_21]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_cfg_pe_21 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(cfg_pe_21_we),
      .wd(cfg_pe_21_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.cfg_pe_21[0].q),

      // to register interface (read)
      .qs(cfg_pe_21_qs)
  );



  // Subregister 0 of Multireg cfg_pe_22
  // R[cfg_pe_22]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_cfg_pe_22 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(cfg_pe_22_we),
      .wd(cfg_pe_22_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.cfg_pe_22[0].q),

      // to register interface (read)
      .qs(cfg_pe_22_qs)
  );



  // Subregister 0 of Multireg cfg_pe_23
  // R[cfg_pe_23]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_cfg_pe_23 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(cfg_pe_23_we),
      .wd(cfg_pe_23_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.cfg_pe_23[0].q),

      // to register interface (read)
      .qs(cfg_pe_23_qs)
  );



  // Subregister 0 of Multireg cfg_pe_30
  // R[cfg_pe_30]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_cfg_pe_30 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(cfg_pe_30_we),
      .wd(cfg_pe_30_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.cfg_pe_30[0].q),

      // to register interface (read)
      .qs(cfg_pe_30_qs)
  );



  // Subregister 0 of Multireg cfg_pe_31
  // R[cfg_pe_31]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_cfg_pe_31 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(cfg_pe_31_we),
      .wd(cfg_pe_31_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.cfg_pe_31[0].q),

      // to register interface (read)
      .qs(cfg_pe_31_qs)
  );



  // Subregister 0 of Multireg cfg_pe_32
  // R[cfg_pe_32]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_cfg_pe_32 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(cfg_pe_32_we),
      .wd(cfg_pe_32_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.cfg_pe_32[0].q),

      // to register interface (read)
      .qs(cfg_pe_32_qs)
  );



  // Subregister 0 of Multireg cfg_pe_33
  // R[cfg_pe_33]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_cfg_pe_33 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(cfg_pe_33_we),
      .wd(cfg_pe_33_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.cfg_pe_33[0].q),

      // to register interface (read)
      .qs(cfg_pe_33_qs)
  );



  // Subregister 0 of Multireg pea_constants
  // R[pea_constants_0]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_pea_constants_0 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(pea_constants_0_we),
      .wd(pea_constants_0_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.pea_constants[0].q),

      // to register interface (read)
      .qs(pea_constants_0_qs)
  );

  // Subregister 1 of Multireg pea_constants
  // R[pea_constants_1]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_pea_constants_1 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(pea_constants_1_we),
      .wd(pea_constants_1_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.pea_constants[1].q),

      // to register interface (read)
      .qs(pea_constants_1_qs)
  );

  // Subregister 2 of Multireg pea_constants
  // R[pea_constants_2]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_pea_constants_2 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(pea_constants_2_we),
      .wd(pea_constants_2_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.pea_constants[2].q),

      // to register interface (read)
      .qs(pea_constants_2_qs)
  );

  // Subregister 3 of Multireg pea_constants
  // R[pea_constants_3]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_pea_constants_3 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(pea_constants_3_we),
      .wd(pea_constants_3_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.pea_constants[3].q),

      // to register interface (read)
      .qs(pea_constants_3_qs)
  );

  // Subregister 4 of Multireg pea_constants
  // R[pea_constants_4]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_pea_constants_4 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(pea_constants_4_we),
      .wd(pea_constants_4_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.pea_constants[4].q),

      // to register interface (read)
      .qs(pea_constants_4_qs)
  );

  // Subregister 5 of Multireg pea_constants
  // R[pea_constants_5]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_pea_constants_5 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(pea_constants_5_we),
      .wd(pea_constants_5_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.pea_constants[5].q),

      // to register interface (read)
      .qs(pea_constants_5_qs)
  );

  // Subregister 6 of Multireg pea_constants
  // R[pea_constants_6]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_pea_constants_6 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(pea_constants_6_we),
      .wd(pea_constants_6_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.pea_constants[6].q),

      // to register interface (read)
      .qs(pea_constants_6_qs)
  );

  // Subregister 7 of Multireg pea_constants
  // R[pea_constants_7]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_pea_constants_7 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(pea_constants_7_we),
      .wd(pea_constants_7_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.pea_constants[7].q),

      // to register interface (read)
      .qs(pea_constants_7_qs)
  );

  // Subregister 8 of Multireg pea_constants
  // R[pea_constants_8]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_pea_constants_8 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(pea_constants_8_we),
      .wd(pea_constants_8_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.pea_constants[8].q),

      // to register interface (read)
      .qs(pea_constants_8_qs)
  );

  // Subregister 9 of Multireg pea_constants
  // R[pea_constants_9]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_pea_constants_9 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(pea_constants_9_we),
      .wd(pea_constants_9_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.pea_constants[9].q),

      // to register interface (read)
      .qs(pea_constants_9_qs)
  );

  // Subregister 10 of Multireg pea_constants
  // R[pea_constants_10]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_pea_constants_10 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(pea_constants_10_we),
      .wd(pea_constants_10_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.pea_constants[10].q),

      // to register interface (read)
      .qs(pea_constants_10_qs)
  );

  // Subregister 11 of Multireg pea_constants
  // R[pea_constants_11]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_pea_constants_11 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(pea_constants_11_we),
      .wd(pea_constants_11_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.pea_constants[11].q),

      // to register interface (read)
      .qs(pea_constants_11_qs)
  );

  // Subregister 12 of Multireg pea_constants
  // R[pea_constants_12]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_pea_constants_12 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(pea_constants_12_we),
      .wd(pea_constants_12_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.pea_constants[12].q),

      // to register interface (read)
      .qs(pea_constants_12_qs)
  );

  // Subregister 13 of Multireg pea_constants
  // R[pea_constants_13]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_pea_constants_13 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(pea_constants_13_we),
      .wd(pea_constants_13_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.pea_constants[13].q),

      // to register interface (read)
      .qs(pea_constants_13_qs)
  );

  // Subregister 14 of Multireg pea_constants
  // R[pea_constants_14]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_pea_constants_14 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(pea_constants_14_we),
      .wd(pea_constants_14_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.pea_constants[14].q),

      // to register interface (read)
      .qs(pea_constants_14_qs)
  );

  // Subregister 15 of Multireg pea_constants
  // R[pea_constants_15]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_pea_constants_15 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(pea_constants_15_we),
      .wd(pea_constants_15_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.pea_constants[15].q),

      // to register interface (read)
      .qs(pea_constants_15_qs)
  );


  // R[stream_dma_cfg]: V(False)

  prim_subreg #(
      .DW      (4),
      .SWACCESS("RW"),
      .RESVAL  (4'h0)
  ) u_stream_dma_cfg (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(stream_dma_cfg_we),
      .wd(stream_dma_cfg_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.stream_dma_cfg.q),

      // to register interface (read)
      .qs(stream_dma_cfg_qs)
  );


  // R[separate_cols]: V(False)

  prim_subreg #(
      .DW      (2),
      .SWACCESS("RW"),
      .RESVAL  (2'h0)
  ) u_separate_cols (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(separate_cols_we),
      .wd(separate_cols_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.separate_cols.q),

      // to register interface (read)
      .qs(separate_cols_qs)
  );



  // Subregister 0 of Multireg sel_out_col_pea
  // R[sel_out_col_pea]: V(False)

  // F[sel_col_0_0]: 7:0
  prim_subreg #(
      .DW      (8),
      .SWACCESS("RW"),
      .RESVAL  (8'h0)
  ) u_sel_out_col_pea_sel_col_0_0 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(sel_out_col_pea_sel_col_0_0_we),
      .wd(sel_out_col_pea_sel_col_0_0_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.sel_out_col_pea[0].sel_col_0.q),

      // to register interface (read)
      .qs(sel_out_col_pea_sel_col_0_0_qs)
  );


  // F[sel_col_1_0]: 15:8
  prim_subreg #(
      .DW      (8),
      .SWACCESS("RW"),
      .RESVAL  (8'h0)
  ) u_sel_out_col_pea_sel_col_1_0 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(sel_out_col_pea_sel_col_1_0_we),
      .wd(sel_out_col_pea_sel_col_1_0_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.sel_out_col_pea[0].sel_col_1.q),

      // to register interface (read)
      .qs(sel_out_col_pea_sel_col_1_0_qs)
  );


  // F[sel_col_2_0]: 23:16
  prim_subreg #(
      .DW      (8),
      .SWACCESS("RW"),
      .RESVAL  (8'h0)
  ) u_sel_out_col_pea_sel_col_2_0 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(sel_out_col_pea_sel_col_2_0_we),
      .wd(sel_out_col_pea_sel_col_2_0_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.sel_out_col_pea[0].sel_col_2.q),

      // to register interface (read)
      .qs(sel_out_col_pea_sel_col_2_0_qs)
  );


  // F[sel_col_3_0]: 31:24
  prim_subreg #(
      .DW      (8),
      .SWACCESS("RW"),
      .RESVAL  (8'h0)
  ) u_sel_out_col_pea_sel_col_3_0 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(sel_out_col_pea_sel_col_3_0_we),
      .wd(sel_out_col_pea_sel_col_3_0_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.sel_out_col_pea[0].sel_col_3.q),

      // to register interface (read)
      .qs(sel_out_col_pea_sel_col_3_0_qs)
  );




  // Subregister 0 of Multireg acc_value
  // R[acc_value_0]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_acc_value_0 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(acc_value_0_we),
      .wd(acc_value_0_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.acc_value[0].q),

      // to register interface (read)
      .qs(acc_value_0_qs)
  );

  // Subregister 1 of Multireg acc_value
  // R[acc_value_1]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_acc_value_1 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(acc_value_1_we),
      .wd(acc_value_1_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.acc_value[1].q),

      // to register interface (read)
      .qs(acc_value_1_qs)
  );

  // Subregister 2 of Multireg acc_value
  // R[acc_value_2]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_acc_value_2 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(acc_value_2_we),
      .wd(acc_value_2_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.acc_value[2].q),

      // to register interface (read)
      .qs(acc_value_2_qs)
  );

  // Subregister 3 of Multireg acc_value
  // R[acc_value_3]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_acc_value_3 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(acc_value_3_we),
      .wd(acc_value_3_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.acc_value[3].q),

      // to register interface (read)
      .qs(acc_value_3_qs)
  );

  // Subregister 4 of Multireg acc_value
  // R[acc_value_4]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_acc_value_4 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(acc_value_4_we),
      .wd(acc_value_4_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.acc_value[4].q),

      // to register interface (read)
      .qs(acc_value_4_qs)
  );

  // Subregister 5 of Multireg acc_value
  // R[acc_value_5]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_acc_value_5 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(acc_value_5_we),
      .wd(acc_value_5_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.acc_value[5].q),

      // to register interface (read)
      .qs(acc_value_5_qs)
  );

  // Subregister 6 of Multireg acc_value
  // R[acc_value_6]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_acc_value_6 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(acc_value_6_we),
      .wd(acc_value_6_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.acc_value[6].q),

      // to register interface (read)
      .qs(acc_value_6_qs)
  );

  // Subregister 7 of Multireg acc_value
  // R[acc_value_7]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_acc_value_7 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(acc_value_7_we),
      .wd(acc_value_7_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.acc_value[7].q),

      // to register interface (read)
      .qs(acc_value_7_qs)
  );

  // Subregister 8 of Multireg acc_value
  // R[acc_value_8]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_acc_value_8 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(acc_value_8_we),
      .wd(acc_value_8_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.acc_value[8].q),

      // to register interface (read)
      .qs(acc_value_8_qs)
  );

  // Subregister 9 of Multireg acc_value
  // R[acc_value_9]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_acc_value_9 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(acc_value_9_we),
      .wd(acc_value_9_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.acc_value[9].q),

      // to register interface (read)
      .qs(acc_value_9_qs)
  );

  // Subregister 10 of Multireg acc_value
  // R[acc_value_10]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_acc_value_10 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(acc_value_10_we),
      .wd(acc_value_10_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.acc_value[10].q),

      // to register interface (read)
      .qs(acc_value_10_qs)
  );

  // Subregister 11 of Multireg acc_value
  // R[acc_value_11]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_acc_value_11 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(acc_value_11_we),
      .wd(acc_value_11_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.acc_value[11].q),

      // to register interface (read)
      .qs(acc_value_11_qs)
  );

  // Subregister 12 of Multireg acc_value
  // R[acc_value_12]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_acc_value_12 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(acc_value_12_we),
      .wd(acc_value_12_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.acc_value[12].q),

      // to register interface (read)
      .qs(acc_value_12_qs)
  );

  // Subregister 13 of Multireg acc_value
  // R[acc_value_13]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_acc_value_13 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(acc_value_13_we),
      .wd(acc_value_13_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.acc_value[13].q),

      // to register interface (read)
      .qs(acc_value_13_qs)
  );

  // Subregister 14 of Multireg acc_value
  // R[acc_value_14]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_acc_value_14 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(acc_value_14_we),
      .wd(acc_value_14_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.acc_value[14].q),

      // to register interface (read)
      .qs(acc_value_14_qs)
  );

  // Subregister 15 of Multireg acc_value
  // R[acc_value_15]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_acc_value_15 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(acc_value_15_we),
      .wd(acc_value_15_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.acc_value[15].q),

      // to register interface (read)
      .qs(acc_value_15_qs)
  );




  logic [50:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == MAGE_CFG_PE_00_OFFSET);
    addr_hit[1] = (reg_addr == MAGE_CFG_PE_01_OFFSET);
    addr_hit[2] = (reg_addr == MAGE_CFG_PE_02_OFFSET);
    addr_hit[3] = (reg_addr == MAGE_CFG_PE_03_OFFSET);
    addr_hit[4] = (reg_addr == MAGE_CFG_PE_10_OFFSET);
    addr_hit[5] = (reg_addr == MAGE_CFG_PE_11_OFFSET);
    addr_hit[6] = (reg_addr == MAGE_CFG_PE_12_OFFSET);
    addr_hit[7] = (reg_addr == MAGE_CFG_PE_13_OFFSET);
    addr_hit[8] = (reg_addr == MAGE_CFG_PE_20_OFFSET);
    addr_hit[9] = (reg_addr == MAGE_CFG_PE_21_OFFSET);
    addr_hit[10] = (reg_addr == MAGE_CFG_PE_22_OFFSET);
    addr_hit[11] = (reg_addr == MAGE_CFG_PE_23_OFFSET);
    addr_hit[12] = (reg_addr == MAGE_CFG_PE_30_OFFSET);
    addr_hit[13] = (reg_addr == MAGE_CFG_PE_31_OFFSET);
    addr_hit[14] = (reg_addr == MAGE_CFG_PE_32_OFFSET);
    addr_hit[15] = (reg_addr == MAGE_CFG_PE_33_OFFSET);
    addr_hit[16] = (reg_addr == MAGE_PEA_CONSTANTS_0_OFFSET);
    addr_hit[17] = (reg_addr == MAGE_PEA_CONSTANTS_1_OFFSET);
    addr_hit[18] = (reg_addr == MAGE_PEA_CONSTANTS_2_OFFSET);
    addr_hit[19] = (reg_addr == MAGE_PEA_CONSTANTS_3_OFFSET);
    addr_hit[20] = (reg_addr == MAGE_PEA_CONSTANTS_4_OFFSET);
    addr_hit[21] = (reg_addr == MAGE_PEA_CONSTANTS_5_OFFSET);
    addr_hit[22] = (reg_addr == MAGE_PEA_CONSTANTS_6_OFFSET);
    addr_hit[23] = (reg_addr == MAGE_PEA_CONSTANTS_7_OFFSET);
    addr_hit[24] = (reg_addr == MAGE_PEA_CONSTANTS_8_OFFSET);
    addr_hit[25] = (reg_addr == MAGE_PEA_CONSTANTS_9_OFFSET);
    addr_hit[26] = (reg_addr == MAGE_PEA_CONSTANTS_10_OFFSET);
    addr_hit[27] = (reg_addr == MAGE_PEA_CONSTANTS_11_OFFSET);
    addr_hit[28] = (reg_addr == MAGE_PEA_CONSTANTS_12_OFFSET);
    addr_hit[29] = (reg_addr == MAGE_PEA_CONSTANTS_13_OFFSET);
    addr_hit[30] = (reg_addr == MAGE_PEA_CONSTANTS_14_OFFSET);
    addr_hit[31] = (reg_addr == MAGE_PEA_CONSTANTS_15_OFFSET);
    addr_hit[32] = (reg_addr == MAGE_STREAM_DMA_CFG_OFFSET);
    addr_hit[33] = (reg_addr == MAGE_SEPARATE_COLS_OFFSET);
    addr_hit[34] = (reg_addr == MAGE_SEL_OUT_COL_PEA_OFFSET);
    addr_hit[35] = (reg_addr == MAGE_ACC_VALUE_0_OFFSET);
    addr_hit[36] = (reg_addr == MAGE_ACC_VALUE_1_OFFSET);
    addr_hit[37] = (reg_addr == MAGE_ACC_VALUE_2_OFFSET);
    addr_hit[38] = (reg_addr == MAGE_ACC_VALUE_3_OFFSET);
    addr_hit[39] = (reg_addr == MAGE_ACC_VALUE_4_OFFSET);
    addr_hit[40] = (reg_addr == MAGE_ACC_VALUE_5_OFFSET);
    addr_hit[41] = (reg_addr == MAGE_ACC_VALUE_6_OFFSET);
    addr_hit[42] = (reg_addr == MAGE_ACC_VALUE_7_OFFSET);
    addr_hit[43] = (reg_addr == MAGE_ACC_VALUE_8_OFFSET);
    addr_hit[44] = (reg_addr == MAGE_ACC_VALUE_9_OFFSET);
    addr_hit[45] = (reg_addr == MAGE_ACC_VALUE_10_OFFSET);
    addr_hit[46] = (reg_addr == MAGE_ACC_VALUE_11_OFFSET);
    addr_hit[47] = (reg_addr == MAGE_ACC_VALUE_12_OFFSET);
    addr_hit[48] = (reg_addr == MAGE_ACC_VALUE_13_OFFSET);
    addr_hit[49] = (reg_addr == MAGE_ACC_VALUE_14_OFFSET);
    addr_hit[50] = (reg_addr == MAGE_ACC_VALUE_15_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[ 0] & (|(MAGE_PERMIT[ 0] & ~reg_be))) |
               (addr_hit[ 1] & (|(MAGE_PERMIT[ 1] & ~reg_be))) |
               (addr_hit[ 2] & (|(MAGE_PERMIT[ 2] & ~reg_be))) |
               (addr_hit[ 3] & (|(MAGE_PERMIT[ 3] & ~reg_be))) |
               (addr_hit[ 4] & (|(MAGE_PERMIT[ 4] & ~reg_be))) |
               (addr_hit[ 5] & (|(MAGE_PERMIT[ 5] & ~reg_be))) |
               (addr_hit[ 6] & (|(MAGE_PERMIT[ 6] & ~reg_be))) |
               (addr_hit[ 7] & (|(MAGE_PERMIT[ 7] & ~reg_be))) |
               (addr_hit[ 8] & (|(MAGE_PERMIT[ 8] & ~reg_be))) |
               (addr_hit[ 9] & (|(MAGE_PERMIT[ 9] & ~reg_be))) |
               (addr_hit[10] & (|(MAGE_PERMIT[10] & ~reg_be))) |
               (addr_hit[11] & (|(MAGE_PERMIT[11] & ~reg_be))) |
               (addr_hit[12] & (|(MAGE_PERMIT[12] & ~reg_be))) |
               (addr_hit[13] & (|(MAGE_PERMIT[13] & ~reg_be))) |
               (addr_hit[14] & (|(MAGE_PERMIT[14] & ~reg_be))) |
               (addr_hit[15] & (|(MAGE_PERMIT[15] & ~reg_be))) |
               (addr_hit[16] & (|(MAGE_PERMIT[16] & ~reg_be))) |
               (addr_hit[17] & (|(MAGE_PERMIT[17] & ~reg_be))) |
               (addr_hit[18] & (|(MAGE_PERMIT[18] & ~reg_be))) |
               (addr_hit[19] & (|(MAGE_PERMIT[19] & ~reg_be))) |
               (addr_hit[20] & (|(MAGE_PERMIT[20] & ~reg_be))) |
               (addr_hit[21] & (|(MAGE_PERMIT[21] & ~reg_be))) |
               (addr_hit[22] & (|(MAGE_PERMIT[22] & ~reg_be))) |
               (addr_hit[23] & (|(MAGE_PERMIT[23] & ~reg_be))) |
               (addr_hit[24] & (|(MAGE_PERMIT[24] & ~reg_be))) |
               (addr_hit[25] & (|(MAGE_PERMIT[25] & ~reg_be))) |
               (addr_hit[26] & (|(MAGE_PERMIT[26] & ~reg_be))) |
               (addr_hit[27] & (|(MAGE_PERMIT[27] & ~reg_be))) |
               (addr_hit[28] & (|(MAGE_PERMIT[28] & ~reg_be))) |
               (addr_hit[29] & (|(MAGE_PERMIT[29] & ~reg_be))) |
               (addr_hit[30] & (|(MAGE_PERMIT[30] & ~reg_be))) |
               (addr_hit[31] & (|(MAGE_PERMIT[31] & ~reg_be))) |
               (addr_hit[32] & (|(MAGE_PERMIT[32] & ~reg_be))) |
               (addr_hit[33] & (|(MAGE_PERMIT[33] & ~reg_be))) |
               (addr_hit[34] & (|(MAGE_PERMIT[34] & ~reg_be))) |
               (addr_hit[35] & (|(MAGE_PERMIT[35] & ~reg_be))) |
               (addr_hit[36] & (|(MAGE_PERMIT[36] & ~reg_be))) |
               (addr_hit[37] & (|(MAGE_PERMIT[37] & ~reg_be))) |
               (addr_hit[38] & (|(MAGE_PERMIT[38] & ~reg_be))) |
               (addr_hit[39] & (|(MAGE_PERMIT[39] & ~reg_be))) |
               (addr_hit[40] & (|(MAGE_PERMIT[40] & ~reg_be))) |
               (addr_hit[41] & (|(MAGE_PERMIT[41] & ~reg_be))) |
               (addr_hit[42] & (|(MAGE_PERMIT[42] & ~reg_be))) |
               (addr_hit[43] & (|(MAGE_PERMIT[43] & ~reg_be))) |
               (addr_hit[44] & (|(MAGE_PERMIT[44] & ~reg_be))) |
               (addr_hit[45] & (|(MAGE_PERMIT[45] & ~reg_be))) |
               (addr_hit[46] & (|(MAGE_PERMIT[46] & ~reg_be))) |
               (addr_hit[47] & (|(MAGE_PERMIT[47] & ~reg_be))) |
               (addr_hit[48] & (|(MAGE_PERMIT[48] & ~reg_be))) |
               (addr_hit[49] & (|(MAGE_PERMIT[49] & ~reg_be))) |
               (addr_hit[50] & (|(MAGE_PERMIT[50] & ~reg_be)))));
  end

  assign cfg_pe_00_we = addr_hit[0] & reg_we & !reg_error;
  assign cfg_pe_00_wd = reg_wdata[31:0];

  assign cfg_pe_01_we = addr_hit[1] & reg_we & !reg_error;
  assign cfg_pe_01_wd = reg_wdata[31:0];

  assign cfg_pe_02_we = addr_hit[2] & reg_we & !reg_error;
  assign cfg_pe_02_wd = reg_wdata[31:0];

  assign cfg_pe_03_we = addr_hit[3] & reg_we & !reg_error;
  assign cfg_pe_03_wd = reg_wdata[31:0];

  assign cfg_pe_10_we = addr_hit[4] & reg_we & !reg_error;
  assign cfg_pe_10_wd = reg_wdata[31:0];

  assign cfg_pe_11_we = addr_hit[5] & reg_we & !reg_error;
  assign cfg_pe_11_wd = reg_wdata[31:0];

  assign cfg_pe_12_we = addr_hit[6] & reg_we & !reg_error;
  assign cfg_pe_12_wd = reg_wdata[31:0];

  assign cfg_pe_13_we = addr_hit[7] & reg_we & !reg_error;
  assign cfg_pe_13_wd = reg_wdata[31:0];

  assign cfg_pe_20_we = addr_hit[8] & reg_we & !reg_error;
  assign cfg_pe_20_wd = reg_wdata[31:0];

  assign cfg_pe_21_we = addr_hit[9] & reg_we & !reg_error;
  assign cfg_pe_21_wd = reg_wdata[31:0];

  assign cfg_pe_22_we = addr_hit[10] & reg_we & !reg_error;
  assign cfg_pe_22_wd = reg_wdata[31:0];

  assign cfg_pe_23_we = addr_hit[11] & reg_we & !reg_error;
  assign cfg_pe_23_wd = reg_wdata[31:0];

  assign cfg_pe_30_we = addr_hit[12] & reg_we & !reg_error;
  assign cfg_pe_30_wd = reg_wdata[31:0];

  assign cfg_pe_31_we = addr_hit[13] & reg_we & !reg_error;
  assign cfg_pe_31_wd = reg_wdata[31:0];

  assign cfg_pe_32_we = addr_hit[14] & reg_we & !reg_error;
  assign cfg_pe_32_wd = reg_wdata[31:0];

  assign cfg_pe_33_we = addr_hit[15] & reg_we & !reg_error;
  assign cfg_pe_33_wd = reg_wdata[31:0];

  assign pea_constants_0_we = addr_hit[16] & reg_we & !reg_error;
  assign pea_constants_0_wd = reg_wdata[31:0];

  assign pea_constants_1_we = addr_hit[17] & reg_we & !reg_error;
  assign pea_constants_1_wd = reg_wdata[31:0];

  assign pea_constants_2_we = addr_hit[18] & reg_we & !reg_error;
  assign pea_constants_2_wd = reg_wdata[31:0];

  assign pea_constants_3_we = addr_hit[19] & reg_we & !reg_error;
  assign pea_constants_3_wd = reg_wdata[31:0];

  assign pea_constants_4_we = addr_hit[20] & reg_we & !reg_error;
  assign pea_constants_4_wd = reg_wdata[31:0];

  assign pea_constants_5_we = addr_hit[21] & reg_we & !reg_error;
  assign pea_constants_5_wd = reg_wdata[31:0];

  assign pea_constants_6_we = addr_hit[22] & reg_we & !reg_error;
  assign pea_constants_6_wd = reg_wdata[31:0];

  assign pea_constants_7_we = addr_hit[23] & reg_we & !reg_error;
  assign pea_constants_7_wd = reg_wdata[31:0];

  assign pea_constants_8_we = addr_hit[24] & reg_we & !reg_error;
  assign pea_constants_8_wd = reg_wdata[31:0];

  assign pea_constants_9_we = addr_hit[25] & reg_we & !reg_error;
  assign pea_constants_9_wd = reg_wdata[31:0];

  assign pea_constants_10_we = addr_hit[26] & reg_we & !reg_error;
  assign pea_constants_10_wd = reg_wdata[31:0];

  assign pea_constants_11_we = addr_hit[27] & reg_we & !reg_error;
  assign pea_constants_11_wd = reg_wdata[31:0];

  assign pea_constants_12_we = addr_hit[28] & reg_we & !reg_error;
  assign pea_constants_12_wd = reg_wdata[31:0];

  assign pea_constants_13_we = addr_hit[29] & reg_we & !reg_error;
  assign pea_constants_13_wd = reg_wdata[31:0];

  assign pea_constants_14_we = addr_hit[30] & reg_we & !reg_error;
  assign pea_constants_14_wd = reg_wdata[31:0];

  assign pea_constants_15_we = addr_hit[31] & reg_we & !reg_error;
  assign pea_constants_15_wd = reg_wdata[31:0];

  assign stream_dma_cfg_we = addr_hit[32] & reg_we & !reg_error;
  assign stream_dma_cfg_wd = reg_wdata[3:0];

  assign separate_cols_we = addr_hit[33] & reg_we & !reg_error;
  assign separate_cols_wd = reg_wdata[1:0];

  assign sel_out_col_pea_sel_col_0_0_we = addr_hit[34] & reg_we & !reg_error;
  assign sel_out_col_pea_sel_col_0_0_wd = reg_wdata[7:0];

  assign sel_out_col_pea_sel_col_1_0_we = addr_hit[34] & reg_we & !reg_error;
  assign sel_out_col_pea_sel_col_1_0_wd = reg_wdata[15:8];

  assign sel_out_col_pea_sel_col_2_0_we = addr_hit[34] & reg_we & !reg_error;
  assign sel_out_col_pea_sel_col_2_0_wd = reg_wdata[23:16];

  assign sel_out_col_pea_sel_col_3_0_we = addr_hit[34] & reg_we & !reg_error;
  assign sel_out_col_pea_sel_col_3_0_wd = reg_wdata[31:24];

  assign acc_value_0_we = addr_hit[35] & reg_we & !reg_error;
  assign acc_value_0_wd = reg_wdata[31:0];

  assign acc_value_1_we = addr_hit[36] & reg_we & !reg_error;
  assign acc_value_1_wd = reg_wdata[31:0];

  assign acc_value_2_we = addr_hit[37] & reg_we & !reg_error;
  assign acc_value_2_wd = reg_wdata[31:0];

  assign acc_value_3_we = addr_hit[38] & reg_we & !reg_error;
  assign acc_value_3_wd = reg_wdata[31:0];

  assign acc_value_4_we = addr_hit[39] & reg_we & !reg_error;
  assign acc_value_4_wd = reg_wdata[31:0];

  assign acc_value_5_we = addr_hit[40] & reg_we & !reg_error;
  assign acc_value_5_wd = reg_wdata[31:0];

  assign acc_value_6_we = addr_hit[41] & reg_we & !reg_error;
  assign acc_value_6_wd = reg_wdata[31:0];

  assign acc_value_7_we = addr_hit[42] & reg_we & !reg_error;
  assign acc_value_7_wd = reg_wdata[31:0];

  assign acc_value_8_we = addr_hit[43] & reg_we & !reg_error;
  assign acc_value_8_wd = reg_wdata[31:0];

  assign acc_value_9_we = addr_hit[44] & reg_we & !reg_error;
  assign acc_value_9_wd = reg_wdata[31:0];

  assign acc_value_10_we = addr_hit[45] & reg_we & !reg_error;
  assign acc_value_10_wd = reg_wdata[31:0];

  assign acc_value_11_we = addr_hit[46] & reg_we & !reg_error;
  assign acc_value_11_wd = reg_wdata[31:0];

  assign acc_value_12_we = addr_hit[47] & reg_we & !reg_error;
  assign acc_value_12_wd = reg_wdata[31:0];

  assign acc_value_13_we = addr_hit[48] & reg_we & !reg_error;
  assign acc_value_13_wd = reg_wdata[31:0];

  assign acc_value_14_we = addr_hit[49] & reg_we & !reg_error;
  assign acc_value_14_wd = reg_wdata[31:0];

  assign acc_value_15_we = addr_hit[50] & reg_we & !reg_error;
  assign acc_value_15_wd = reg_wdata[31:0];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[31:0] = cfg_pe_00_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[31:0] = cfg_pe_01_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[31:0] = cfg_pe_02_qs;
      end

      addr_hit[3]: begin
        reg_rdata_next[31:0] = cfg_pe_03_qs;
      end

      addr_hit[4]: begin
        reg_rdata_next[31:0] = cfg_pe_10_qs;
      end

      addr_hit[5]: begin
        reg_rdata_next[31:0] = cfg_pe_11_qs;
      end

      addr_hit[6]: begin
        reg_rdata_next[31:0] = cfg_pe_12_qs;
      end

      addr_hit[7]: begin
        reg_rdata_next[31:0] = cfg_pe_13_qs;
      end

      addr_hit[8]: begin
        reg_rdata_next[31:0] = cfg_pe_20_qs;
      end

      addr_hit[9]: begin
        reg_rdata_next[31:0] = cfg_pe_21_qs;
      end

      addr_hit[10]: begin
        reg_rdata_next[31:0] = cfg_pe_22_qs;
      end

      addr_hit[11]: begin
        reg_rdata_next[31:0] = cfg_pe_23_qs;
      end

      addr_hit[12]: begin
        reg_rdata_next[31:0] = cfg_pe_30_qs;
      end

      addr_hit[13]: begin
        reg_rdata_next[31:0] = cfg_pe_31_qs;
      end

      addr_hit[14]: begin
        reg_rdata_next[31:0] = cfg_pe_32_qs;
      end

      addr_hit[15]: begin
        reg_rdata_next[31:0] = cfg_pe_33_qs;
      end

      addr_hit[16]: begin
        reg_rdata_next[31:0] = pea_constants_0_qs;
      end

      addr_hit[17]: begin
        reg_rdata_next[31:0] = pea_constants_1_qs;
      end

      addr_hit[18]: begin
        reg_rdata_next[31:0] = pea_constants_2_qs;
      end

      addr_hit[19]: begin
        reg_rdata_next[31:0] = pea_constants_3_qs;
      end

      addr_hit[20]: begin
        reg_rdata_next[31:0] = pea_constants_4_qs;
      end

      addr_hit[21]: begin
        reg_rdata_next[31:0] = pea_constants_5_qs;
      end

      addr_hit[22]: begin
        reg_rdata_next[31:0] = pea_constants_6_qs;
      end

      addr_hit[23]: begin
        reg_rdata_next[31:0] = pea_constants_7_qs;
      end

      addr_hit[24]: begin
        reg_rdata_next[31:0] = pea_constants_8_qs;
      end

      addr_hit[25]: begin
        reg_rdata_next[31:0] = pea_constants_9_qs;
      end

      addr_hit[26]: begin
        reg_rdata_next[31:0] = pea_constants_10_qs;
      end

      addr_hit[27]: begin
        reg_rdata_next[31:0] = pea_constants_11_qs;
      end

      addr_hit[28]: begin
        reg_rdata_next[31:0] = pea_constants_12_qs;
      end

      addr_hit[29]: begin
        reg_rdata_next[31:0] = pea_constants_13_qs;
      end

      addr_hit[30]: begin
        reg_rdata_next[31:0] = pea_constants_14_qs;
      end

      addr_hit[31]: begin
        reg_rdata_next[31:0] = pea_constants_15_qs;
      end

      addr_hit[32]: begin
        reg_rdata_next[3:0] = stream_dma_cfg_qs;
      end

      addr_hit[33]: begin
        reg_rdata_next[1:0] = separate_cols_qs;
      end

      addr_hit[34]: begin
        reg_rdata_next[7:0]   = sel_out_col_pea_sel_col_0_0_qs;
        reg_rdata_next[15:8]  = sel_out_col_pea_sel_col_1_0_qs;
        reg_rdata_next[23:16] = sel_out_col_pea_sel_col_2_0_qs;
        reg_rdata_next[31:24] = sel_out_col_pea_sel_col_3_0_qs;
      end

      addr_hit[35]: begin
        reg_rdata_next[31:0] = acc_value_0_qs;
      end

      addr_hit[36]: begin
        reg_rdata_next[31:0] = acc_value_1_qs;
      end

      addr_hit[37]: begin
        reg_rdata_next[31:0] = acc_value_2_qs;
      end

      addr_hit[38]: begin
        reg_rdata_next[31:0] = acc_value_3_qs;
      end

      addr_hit[39]: begin
        reg_rdata_next[31:0] = acc_value_4_qs;
      end

      addr_hit[40]: begin
        reg_rdata_next[31:0] = acc_value_5_qs;
      end

      addr_hit[41]: begin
        reg_rdata_next[31:0] = acc_value_6_qs;
      end

      addr_hit[42]: begin
        reg_rdata_next[31:0] = acc_value_7_qs;
      end

      addr_hit[43]: begin
        reg_rdata_next[31:0] = acc_value_8_qs;
      end

      addr_hit[44]: begin
        reg_rdata_next[31:0] = acc_value_9_qs;
      end

      addr_hit[45]: begin
        reg_rdata_next[31:0] = acc_value_10_qs;
      end

      addr_hit[46]: begin
        reg_rdata_next[31:0] = acc_value_11_qs;
      end

      addr_hit[47]: begin
        reg_rdata_next[31:0] = acc_value_12_qs;
      end

      addr_hit[48]: begin
        reg_rdata_next[31:0] = acc_value_13_qs;
      end

      addr_hit[49]: begin
        reg_rdata_next[31:0] = acc_value_14_qs;
      end

      addr_hit[50]: begin
        reg_rdata_next[31:0] = acc_value_15_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule

module mage_reg_top_intf #(
    parameter  int AW = 8,
    localparam int DW = 32
) (
    input logic clk_i,
    input logic rst_ni,
    REG_BUS.in regbus_slave,
    // To HW
    output mage_reg_pkg::mage_reg2hw_t reg2hw,  // Write
    // Config
    input devmode_i  // If 1, explicit error return for unmapped register access
);
  localparam int unsigned STRB_WIDTH = DW / 8;

  `include "register_interface/typedef.svh"
  `include "register_interface/assign.svh"

  // Define structs for reg_bus
  typedef logic [AW-1:0] addr_t;
  typedef logic [DW-1:0] data_t;
  typedef logic [STRB_WIDTH-1:0] strb_t;
  `REG_BUS_TYPEDEF_ALL(reg_bus, addr_t, data_t, strb_t)

  reg_bus_req_t s_reg_req;
  reg_bus_rsp_t s_reg_rsp;

  // Assign SV interface to structs
  `REG_BUS_ASSIGN_TO_REQ(s_reg_req, regbus_slave)
  `REG_BUS_ASSIGN_FROM_RSP(regbus_slave, s_reg_rsp)



  mage_reg_top #(
      .reg_req_t(reg_bus_req_t),
      .reg_rsp_t(reg_bus_rsp_t),
      .AW(AW)
  ) i_regs (
      .clk_i,
      .rst_ni,
      .reg_req_i(s_reg_req),
      .reg_rsp_o(s_reg_rsp),
      .reg2hw,  // Write
      .devmode_i
  );

endmodule


