// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package mage_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 9;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {logic q;} start;
    struct packed {logic q;} done;
  } mage_reg2hw_status_reg_t;

  typedef struct packed {
    struct packed {logic [3:0] q;} ii;
    struct packed {logic q;} s_n_t_mage;
    struct packed {logic q;} s_n_t_mage_pea;
    struct packed {logic q;} s_n_t_mage_pea_out_regs;
    struct packed {logic q;} s_n_t_mage_xbar;
    struct packed {logic [3:0] q;} acc_vec_mode;
    struct packed {logic [3:0] q;} blocksize;
  } mage_reg2hw_gen_cfg_reg_t;

  typedef struct packed {
    struct packed {logic [7:0] q;} ilb_0;
    struct packed {logic [7:0] q;} ilb_1;
    struct packed {logic [7:0] q;} ilb_2;
    struct packed {logic [7:0] q;} ilb_3;
  } mage_reg2hw_ilb_hwl_reg_t;

  typedef struct packed {
    struct packed {logic [7:0] q;} flb_0;
    struct packed {logic [7:0] q;} flb_1;
    struct packed {logic [7:0] q;} flb_2;
    struct packed {logic [7:0] q;} flb_3;
  } mage_reg2hw_flb_hwl_reg_t;

  typedef struct packed {
    struct packed {logic [7:0] q;} inc_0;
    struct packed {logic [7:0] q;} inc_1;
    struct packed {logic [7:0] q;} inc_2;
    struct packed {logic [7:0] q;} inc_3;
  } mage_reg2hw_inc_hwl_reg_t;

  typedef struct packed {
    struct packed {logic [7:0] q;} s0;
    struct packed {logic [7:0] q;} s1;
    struct packed {logic [7:0] q;} s2;
    struct packed {logic [7:0] q;} s3;
  } mage_reg2hw_strides_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_pe_00_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_pe_01_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_pe_02_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_pe_03_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_pe_10_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_pe_11_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_pe_12_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_pe_13_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_pe_20_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_pe_21_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_pe_22_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_pe_23_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_pe_30_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_pe_31_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_pe_32_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_pe_33_mreg_t;

  typedef struct packed {logic [1:0] q;} mage_reg2hw_sel_out_pea_row_0_0_mreg_t;

  typedef struct packed {logic [1:0] q;} mage_reg2hw_sel_out_pea_row_0_1_mreg_t;

  typedef struct packed {logic [1:0] q;} mage_reg2hw_sel_out_pea_row_1_0_mreg_t;

  typedef struct packed {logic [1:0] q;} mage_reg2hw_sel_out_pea_row_1_1_mreg_t;

  typedef struct packed {logic [1:0] q;} mage_reg2hw_sel_out_pea_row_2_0_mreg_t;

  typedef struct packed {logic [1:0] q;} mage_reg2hw_sel_out_pea_row_2_1_mreg_t;

  typedef struct packed {logic [1:0] q;} mage_reg2hw_sel_out_pea_row_3_0_mreg_t;

  typedef struct packed {logic [1:0] q;} mage_reg2hw_sel_out_pea_row_3_1_mreg_t;

  typedef struct packed {logic q;} mage_reg2hw_sel_load_stream_age_0_0_mreg_t;

  typedef struct packed {logic q;} mage_reg2hw_sel_load_stream_age_0_1_mreg_t;

  typedef struct packed {logic q;} mage_reg2hw_sel_load_stream_age_1_0_mreg_t;

  typedef struct packed {logic q;} mage_reg2hw_sel_load_stream_age_1_1_mreg_t;

  typedef struct packed {logic q;} mage_reg2hw_sel_load_stream_age_2_0_mreg_t;

  typedef struct packed {logic q;} mage_reg2hw_sel_load_stream_age_2_1_mreg_t;

  typedef struct packed {logic q;} mage_reg2hw_sel_load_stream_age_3_0_mreg_t;

  typedef struct packed {logic q;} mage_reg2hw_sel_load_stream_age_3_1_mreg_t;

  typedef struct packed {logic q;} mage_reg2hw_sel_store_stream_age_0_0_mreg_t;

  typedef struct packed {logic q;} mage_reg2hw_sel_store_stream_age_0_1_mreg_t;

  typedef struct packed {logic q;} mage_reg2hw_sel_store_stream_age_1_0_mreg_t;

  typedef struct packed {logic q;} mage_reg2hw_sel_store_stream_age_1_1_mreg_t;

  typedef struct packed {logic q;} mage_reg2hw_sel_store_stream_age_2_0_mreg_t;

  typedef struct packed {logic q;} mage_reg2hw_sel_store_stream_age_2_1_mreg_t;

  typedef struct packed {logic q;} mage_reg2hw_sel_store_stream_age_3_0_mreg_t;

  typedef struct packed {logic q;} mage_reg2hw_sel_store_stream_age_3_1_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_mage_s0_age0_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_mage_s0_age1_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_mage_s1_age0_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_mage_s1_age1_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_mage_s2_age0_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_mage_s2_age1_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_mage_s3_age0_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_cfg_mage_s3_age1_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_pea_constants_mreg_t;

  typedef struct packed {logic [31:0] q;} mage_reg2hw_pea_rf_mreg_t;

  typedef struct packed {
    struct packed {logic [7:0] q;} c0;
    struct packed {logic [7:0] q;} c1;
    struct packed {logic [7:0] q;} c2;
    struct packed {logic [7:0] q;} c3;
  } mage_reg2hw_age_iv_constraints_mreg_t;

  typedef struct packed {
    struct packed {
      logic d;
      logic de;
    } start;
    struct packed {
      logic d;
      logic de;
    } done;
  } mage_hw2reg_status_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } mage_hw2reg_pea_rf_mreg_t;

  // Register -> HW type
  typedef struct packed {
    mage_reg2hw_status_reg_t status;  // [2257:2256]
    mage_reg2hw_gen_cfg_reg_t gen_cfg;  // [2255:2240]
    mage_reg2hw_ilb_hwl_reg_t ilb_hwl;  // [2239:2208]
    mage_reg2hw_flb_hwl_reg_t flb_hwl;  // [2207:2176]
    mage_reg2hw_inc_hwl_reg_t inc_hwl;  // [2175:2144]
    mage_reg2hw_strides_mreg_t [7:0] strides;  // [2143:1888]
    mage_reg2hw_cfg_pe_00_mreg_t [0:0] cfg_pe_00;  // [1887:1856]
    mage_reg2hw_cfg_pe_01_mreg_t [0:0] cfg_pe_01;  // [1855:1824]
    mage_reg2hw_cfg_pe_02_mreg_t [0:0] cfg_pe_02;  // [1823:1792]
    mage_reg2hw_cfg_pe_03_mreg_t [0:0] cfg_pe_03;  // [1791:1760]
    mage_reg2hw_cfg_pe_10_mreg_t [0:0] cfg_pe_10;  // [1759:1728]
    mage_reg2hw_cfg_pe_11_mreg_t [0:0] cfg_pe_11;  // [1727:1696]
    mage_reg2hw_cfg_pe_12_mreg_t [0:0] cfg_pe_12;  // [1695:1664]
    mage_reg2hw_cfg_pe_13_mreg_t [0:0] cfg_pe_13;  // [1663:1632]
    mage_reg2hw_cfg_pe_20_mreg_t [0:0] cfg_pe_20;  // [1631:1600]
    mage_reg2hw_cfg_pe_21_mreg_t [0:0] cfg_pe_21;  // [1599:1568]
    mage_reg2hw_cfg_pe_22_mreg_t [0:0] cfg_pe_22;  // [1567:1536]
    mage_reg2hw_cfg_pe_23_mreg_t [0:0] cfg_pe_23;  // [1535:1504]
    mage_reg2hw_cfg_pe_30_mreg_t [0:0] cfg_pe_30;  // [1503:1472]
    mage_reg2hw_cfg_pe_31_mreg_t [0:0] cfg_pe_31;  // [1471:1440]
    mage_reg2hw_cfg_pe_32_mreg_t [0:0] cfg_pe_32;  // [1439:1408]
    mage_reg2hw_cfg_pe_33_mreg_t [0:0] cfg_pe_33;  // [1407:1376]
    mage_reg2hw_sel_out_pea_row_0_0_mreg_t [0:0] sel_out_pea_row_0_0;  // [1375:1374]
    mage_reg2hw_sel_out_pea_row_0_1_mreg_t [0:0] sel_out_pea_row_0_1;  // [1373:1372]
    mage_reg2hw_sel_out_pea_row_1_0_mreg_t [0:0] sel_out_pea_row_1_0;  // [1371:1370]
    mage_reg2hw_sel_out_pea_row_1_1_mreg_t [0:0] sel_out_pea_row_1_1;  // [1369:1368]
    mage_reg2hw_sel_out_pea_row_2_0_mreg_t [0:0] sel_out_pea_row_2_0;  // [1367:1366]
    mage_reg2hw_sel_out_pea_row_2_1_mreg_t [0:0] sel_out_pea_row_2_1;  // [1365:1364]
    mage_reg2hw_sel_out_pea_row_3_0_mreg_t [0:0] sel_out_pea_row_3_0;  // [1363:1362]
    mage_reg2hw_sel_out_pea_row_3_1_mreg_t [0:0] sel_out_pea_row_3_1;  // [1361:1360]
    mage_reg2hw_sel_load_stream_age_0_0_mreg_t [0:0] sel_load_stream_age_0_0;  // [1359:1359]
    mage_reg2hw_sel_load_stream_age_0_1_mreg_t [0:0] sel_load_stream_age_0_1;  // [1358:1358]
    mage_reg2hw_sel_load_stream_age_1_0_mreg_t [0:0] sel_load_stream_age_1_0;  // [1357:1357]
    mage_reg2hw_sel_load_stream_age_1_1_mreg_t [0:0] sel_load_stream_age_1_1;  // [1356:1356]
    mage_reg2hw_sel_load_stream_age_2_0_mreg_t [0:0] sel_load_stream_age_2_0;  // [1355:1355]
    mage_reg2hw_sel_load_stream_age_2_1_mreg_t [0:0] sel_load_stream_age_2_1;  // [1354:1354]
    mage_reg2hw_sel_load_stream_age_3_0_mreg_t [0:0] sel_load_stream_age_3_0;  // [1353:1353]
    mage_reg2hw_sel_load_stream_age_3_1_mreg_t [0:0] sel_load_stream_age_3_1;  // [1352:1352]
    mage_reg2hw_sel_store_stream_age_0_0_mreg_t [0:0] sel_store_stream_age_0_0;  // [1351:1351]
    mage_reg2hw_sel_store_stream_age_0_1_mreg_t [0:0] sel_store_stream_age_0_1;  // [1350:1350]
    mage_reg2hw_sel_store_stream_age_1_0_mreg_t [0:0] sel_store_stream_age_1_0;  // [1349:1349]
    mage_reg2hw_sel_store_stream_age_1_1_mreg_t [0:0] sel_store_stream_age_1_1;  // [1348:1348]
    mage_reg2hw_sel_store_stream_age_2_0_mreg_t [0:0] sel_store_stream_age_2_0;  // [1347:1347]
    mage_reg2hw_sel_store_stream_age_2_1_mreg_t [0:0] sel_store_stream_age_2_1;  // [1346:1346]
    mage_reg2hw_sel_store_stream_age_3_0_mreg_t [0:0] sel_store_stream_age_3_0;  // [1345:1345]
    mage_reg2hw_sel_store_stream_age_3_1_mreg_t [0:0] sel_store_stream_age_3_1;  // [1344:1344]
    mage_reg2hw_cfg_mage_s0_age0_mreg_t [0:0] cfg_mage_s0_age0;  // [1343:1312]
    mage_reg2hw_cfg_mage_s0_age1_mreg_t [0:0] cfg_mage_s0_age1;  // [1311:1280]
    mage_reg2hw_cfg_mage_s1_age0_mreg_t [0:0] cfg_mage_s1_age0;  // [1279:1248]
    mage_reg2hw_cfg_mage_s1_age1_mreg_t [0:0] cfg_mage_s1_age1;  // [1247:1216]
    mage_reg2hw_cfg_mage_s2_age0_mreg_t [0:0] cfg_mage_s2_age0;  // [1215:1184]
    mage_reg2hw_cfg_mage_s2_age1_mreg_t [0:0] cfg_mage_s2_age1;  // [1183:1152]
    mage_reg2hw_cfg_mage_s3_age0_mreg_t [0:0] cfg_mage_s3_age0;  // [1151:1120]
    mage_reg2hw_cfg_mage_s3_age1_mreg_t [0:0] cfg_mage_s3_age1;  // [1119:1088]
    mage_reg2hw_pea_constants_mreg_t [15:0] pea_constants;  // [1087:576]
    mage_reg2hw_pea_rf_mreg_t [15:0] pea_rf;  // [575:64]
    mage_reg2hw_age_iv_constraints_mreg_t [1:0] age_iv_constraints;  // [63:0]
  } mage_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    mage_hw2reg_status_reg_t status;  // [531:528]
    mage_hw2reg_pea_rf_mreg_t [15:0] pea_rf;  // [527:0]
  } mage_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] MAGE_STATUS_OFFSET = 9'h0;
  parameter logic [BlockAw-1:0] MAGE_GEN_CFG_OFFSET = 9'h4;
  parameter logic [BlockAw-1:0] MAGE_ILB_HWL_OFFSET = 9'h8;
  parameter logic [BlockAw-1:0] MAGE_FLB_HWL_OFFSET = 9'hc;
  parameter logic [BlockAw-1:0] MAGE_INC_HWL_OFFSET = 9'h10;
  parameter logic [BlockAw-1:0] MAGE_STRIDES_0_OFFSET = 9'h14;
  parameter logic [BlockAw-1:0] MAGE_STRIDES_1_OFFSET = 9'h18;
  parameter logic [BlockAw-1:0] MAGE_STRIDES_2_OFFSET = 9'h1c;
  parameter logic [BlockAw-1:0] MAGE_STRIDES_3_OFFSET = 9'h20;
  parameter logic [BlockAw-1:0] MAGE_STRIDES_4_OFFSET = 9'h24;
  parameter logic [BlockAw-1:0] MAGE_STRIDES_5_OFFSET = 9'h28;
  parameter logic [BlockAw-1:0] MAGE_STRIDES_6_OFFSET = 9'h2c;
  parameter logic [BlockAw-1:0] MAGE_STRIDES_7_OFFSET = 9'h30;
  parameter logic [BlockAw-1:0] MAGE_CFG_PE_00_OFFSET = 9'h34;
  parameter logic [BlockAw-1:0] MAGE_CFG_PE_01_OFFSET = 9'h38;
  parameter logic [BlockAw-1:0] MAGE_CFG_PE_02_OFFSET = 9'h3c;
  parameter logic [BlockAw-1:0] MAGE_CFG_PE_03_OFFSET = 9'h40;
  parameter logic [BlockAw-1:0] MAGE_CFG_PE_10_OFFSET = 9'h44;
  parameter logic [BlockAw-1:0] MAGE_CFG_PE_11_OFFSET = 9'h48;
  parameter logic [BlockAw-1:0] MAGE_CFG_PE_12_OFFSET = 9'h4c;
  parameter logic [BlockAw-1:0] MAGE_CFG_PE_13_OFFSET = 9'h50;
  parameter logic [BlockAw-1:0] MAGE_CFG_PE_20_OFFSET = 9'h54;
  parameter logic [BlockAw-1:0] MAGE_CFG_PE_21_OFFSET = 9'h58;
  parameter logic [BlockAw-1:0] MAGE_CFG_PE_22_OFFSET = 9'h5c;
  parameter logic [BlockAw-1:0] MAGE_CFG_PE_23_OFFSET = 9'h60;
  parameter logic [BlockAw-1:0] MAGE_CFG_PE_30_OFFSET = 9'h64;
  parameter logic [BlockAw-1:0] MAGE_CFG_PE_31_OFFSET = 9'h68;
  parameter logic [BlockAw-1:0] MAGE_CFG_PE_32_OFFSET = 9'h6c;
  parameter logic [BlockAw-1:0] MAGE_CFG_PE_33_OFFSET = 9'h70;
  parameter logic [BlockAw-1:0] MAGE_SEL_OUT_PEA_ROW_0_0_OFFSET = 9'h74;
  parameter logic [BlockAw-1:0] MAGE_SEL_OUT_PEA_ROW_0_1_OFFSET = 9'h78;
  parameter logic [BlockAw-1:0] MAGE_SEL_OUT_PEA_ROW_1_0_OFFSET = 9'h7c;
  parameter logic [BlockAw-1:0] MAGE_SEL_OUT_PEA_ROW_1_1_OFFSET = 9'h80;
  parameter logic [BlockAw-1:0] MAGE_SEL_OUT_PEA_ROW_2_0_OFFSET = 9'h84;
  parameter logic [BlockAw-1:0] MAGE_SEL_OUT_PEA_ROW_2_1_OFFSET = 9'h88;
  parameter logic [BlockAw-1:0] MAGE_SEL_OUT_PEA_ROW_3_0_OFFSET = 9'h8c;
  parameter logic [BlockAw-1:0] MAGE_SEL_OUT_PEA_ROW_3_1_OFFSET = 9'h90;
  parameter logic [BlockAw-1:0] MAGE_SEL_LOAD_STREAM_AGE_0_0_OFFSET = 9'h94;
  parameter logic [BlockAw-1:0] MAGE_SEL_LOAD_STREAM_AGE_0_1_OFFSET = 9'h98;
  parameter logic [BlockAw-1:0] MAGE_SEL_LOAD_STREAM_AGE_1_0_OFFSET = 9'h9c;
  parameter logic [BlockAw-1:0] MAGE_SEL_LOAD_STREAM_AGE_1_1_OFFSET = 9'ha0;
  parameter logic [BlockAw-1:0] MAGE_SEL_LOAD_STREAM_AGE_2_0_OFFSET = 9'ha4;
  parameter logic [BlockAw-1:0] MAGE_SEL_LOAD_STREAM_AGE_2_1_OFFSET = 9'ha8;
  parameter logic [BlockAw-1:0] MAGE_SEL_LOAD_STREAM_AGE_3_0_OFFSET = 9'hac;
  parameter logic [BlockAw-1:0] MAGE_SEL_LOAD_STREAM_AGE_3_1_OFFSET = 9'hb0;
  parameter logic [BlockAw-1:0] MAGE_SEL_STORE_STREAM_AGE_0_0_OFFSET = 9'hb4;
  parameter logic [BlockAw-1:0] MAGE_SEL_STORE_STREAM_AGE_0_1_OFFSET = 9'hb8;
  parameter logic [BlockAw-1:0] MAGE_SEL_STORE_STREAM_AGE_1_0_OFFSET = 9'hbc;
  parameter logic [BlockAw-1:0] MAGE_SEL_STORE_STREAM_AGE_1_1_OFFSET = 9'hc0;
  parameter logic [BlockAw-1:0] MAGE_SEL_STORE_STREAM_AGE_2_0_OFFSET = 9'hc4;
  parameter logic [BlockAw-1:0] MAGE_SEL_STORE_STREAM_AGE_2_1_OFFSET = 9'hc8;
  parameter logic [BlockAw-1:0] MAGE_SEL_STORE_STREAM_AGE_3_0_OFFSET = 9'hcc;
  parameter logic [BlockAw-1:0] MAGE_SEL_STORE_STREAM_AGE_3_1_OFFSET = 9'hd0;
  parameter logic [BlockAw-1:0] MAGE_CFG_MAGE_S0_AGE0_OFFSET = 9'hd4;
  parameter logic [BlockAw-1:0] MAGE_CFG_MAGE_S0_AGE1_OFFSET = 9'hd8;
  parameter logic [BlockAw-1:0] MAGE_CFG_MAGE_S1_AGE0_OFFSET = 9'hdc;
  parameter logic [BlockAw-1:0] MAGE_CFG_MAGE_S1_AGE1_OFFSET = 9'he0;
  parameter logic [BlockAw-1:0] MAGE_CFG_MAGE_S2_AGE0_OFFSET = 9'he4;
  parameter logic [BlockAw-1:0] MAGE_CFG_MAGE_S2_AGE1_OFFSET = 9'he8;
  parameter logic [BlockAw-1:0] MAGE_CFG_MAGE_S3_AGE0_OFFSET = 9'hec;
  parameter logic [BlockAw-1:0] MAGE_CFG_MAGE_S3_AGE1_OFFSET = 9'hf0;
  parameter logic [BlockAw-1:0] MAGE_PEA_CONSTANTS_0_OFFSET = 9'hf4;
  parameter logic [BlockAw-1:0] MAGE_PEA_CONSTANTS_1_OFFSET = 9'hf8;
  parameter logic [BlockAw-1:0] MAGE_PEA_CONSTANTS_2_OFFSET = 9'hfc;
  parameter logic [BlockAw-1:0] MAGE_PEA_CONSTANTS_3_OFFSET = 9'h100;
  parameter logic [BlockAw-1:0] MAGE_PEA_CONSTANTS_4_OFFSET = 9'h104;
  parameter logic [BlockAw-1:0] MAGE_PEA_CONSTANTS_5_OFFSET = 9'h108;
  parameter logic [BlockAw-1:0] MAGE_PEA_CONSTANTS_6_OFFSET = 9'h10c;
  parameter logic [BlockAw-1:0] MAGE_PEA_CONSTANTS_7_OFFSET = 9'h110;
  parameter logic [BlockAw-1:0] MAGE_PEA_CONSTANTS_8_OFFSET = 9'h114;
  parameter logic [BlockAw-1:0] MAGE_PEA_CONSTANTS_9_OFFSET = 9'h118;
  parameter logic [BlockAw-1:0] MAGE_PEA_CONSTANTS_10_OFFSET = 9'h11c;
  parameter logic [BlockAw-1:0] MAGE_PEA_CONSTANTS_11_OFFSET = 9'h120;
  parameter logic [BlockAw-1:0] MAGE_PEA_CONSTANTS_12_OFFSET = 9'h124;
  parameter logic [BlockAw-1:0] MAGE_PEA_CONSTANTS_13_OFFSET = 9'h128;
  parameter logic [BlockAw-1:0] MAGE_PEA_CONSTANTS_14_OFFSET = 9'h12c;
  parameter logic [BlockAw-1:0] MAGE_PEA_CONSTANTS_15_OFFSET = 9'h130;
  parameter logic [BlockAw-1:0] MAGE_PEA_RF_0_OFFSET = 9'h134;
  parameter logic [BlockAw-1:0] MAGE_PEA_RF_1_OFFSET = 9'h138;
  parameter logic [BlockAw-1:0] MAGE_PEA_RF_2_OFFSET = 9'h13c;
  parameter logic [BlockAw-1:0] MAGE_PEA_RF_3_OFFSET = 9'h140;
  parameter logic [BlockAw-1:0] MAGE_PEA_RF_4_OFFSET = 9'h144;
  parameter logic [BlockAw-1:0] MAGE_PEA_RF_5_OFFSET = 9'h148;
  parameter logic [BlockAw-1:0] MAGE_PEA_RF_6_OFFSET = 9'h14c;
  parameter logic [BlockAw-1:0] MAGE_PEA_RF_7_OFFSET = 9'h150;
  parameter logic [BlockAw-1:0] MAGE_PEA_RF_8_OFFSET = 9'h154;
  parameter logic [BlockAw-1:0] MAGE_PEA_RF_9_OFFSET = 9'h158;
  parameter logic [BlockAw-1:0] MAGE_PEA_RF_10_OFFSET = 9'h15c;
  parameter logic [BlockAw-1:0] MAGE_PEA_RF_11_OFFSET = 9'h160;
  parameter logic [BlockAw-1:0] MAGE_PEA_RF_12_OFFSET = 9'h164;
  parameter logic [BlockAw-1:0] MAGE_PEA_RF_13_OFFSET = 9'h168;
  parameter logic [BlockAw-1:0] MAGE_PEA_RF_14_OFFSET = 9'h16c;
  parameter logic [BlockAw-1:0] MAGE_PEA_RF_15_OFFSET = 9'h170;
  parameter logic [BlockAw-1:0] MAGE_AGE_IV_CONSTRAINTS_0_OFFSET = 9'h174;
  parameter logic [BlockAw-1:0] MAGE_AGE_IV_CONSTRAINTS_1_OFFSET = 9'h178;

  // Register index
  typedef enum int {
    MAGE_STATUS,
    MAGE_GEN_CFG,
    MAGE_ILB_HWL,
    MAGE_FLB_HWL,
    MAGE_INC_HWL,
    MAGE_STRIDES_0,
    MAGE_STRIDES_1,
    MAGE_STRIDES_2,
    MAGE_STRIDES_3,
    MAGE_STRIDES_4,
    MAGE_STRIDES_5,
    MAGE_STRIDES_6,
    MAGE_STRIDES_7,
    MAGE_CFG_PE_00,
    MAGE_CFG_PE_01,
    MAGE_CFG_PE_02,
    MAGE_CFG_PE_03,
    MAGE_CFG_PE_10,
    MAGE_CFG_PE_11,
    MAGE_CFG_PE_12,
    MAGE_CFG_PE_13,
    MAGE_CFG_PE_20,
    MAGE_CFG_PE_21,
    MAGE_CFG_PE_22,
    MAGE_CFG_PE_23,
    MAGE_CFG_PE_30,
    MAGE_CFG_PE_31,
    MAGE_CFG_PE_32,
    MAGE_CFG_PE_33,
    MAGE_SEL_OUT_PEA_ROW_0_0,
    MAGE_SEL_OUT_PEA_ROW_0_1,
    MAGE_SEL_OUT_PEA_ROW_1_0,
    MAGE_SEL_OUT_PEA_ROW_1_1,
    MAGE_SEL_OUT_PEA_ROW_2_0,
    MAGE_SEL_OUT_PEA_ROW_2_1,
    MAGE_SEL_OUT_PEA_ROW_3_0,
    MAGE_SEL_OUT_PEA_ROW_3_1,
    MAGE_SEL_LOAD_STREAM_AGE_0_0,
    MAGE_SEL_LOAD_STREAM_AGE_0_1,
    MAGE_SEL_LOAD_STREAM_AGE_1_0,
    MAGE_SEL_LOAD_STREAM_AGE_1_1,
    MAGE_SEL_LOAD_STREAM_AGE_2_0,
    MAGE_SEL_LOAD_STREAM_AGE_2_1,
    MAGE_SEL_LOAD_STREAM_AGE_3_0,
    MAGE_SEL_LOAD_STREAM_AGE_3_1,
    MAGE_SEL_STORE_STREAM_AGE_0_0,
    MAGE_SEL_STORE_STREAM_AGE_0_1,
    MAGE_SEL_STORE_STREAM_AGE_1_0,
    MAGE_SEL_STORE_STREAM_AGE_1_1,
    MAGE_SEL_STORE_STREAM_AGE_2_0,
    MAGE_SEL_STORE_STREAM_AGE_2_1,
    MAGE_SEL_STORE_STREAM_AGE_3_0,
    MAGE_SEL_STORE_STREAM_AGE_3_1,
    MAGE_CFG_MAGE_S0_AGE0,
    MAGE_CFG_MAGE_S0_AGE1,
    MAGE_CFG_MAGE_S1_AGE0,
    MAGE_CFG_MAGE_S1_AGE1,
    MAGE_CFG_MAGE_S2_AGE0,
    MAGE_CFG_MAGE_S2_AGE1,
    MAGE_CFG_MAGE_S3_AGE0,
    MAGE_CFG_MAGE_S3_AGE1,
    MAGE_PEA_CONSTANTS_0,
    MAGE_PEA_CONSTANTS_1,
    MAGE_PEA_CONSTANTS_2,
    MAGE_PEA_CONSTANTS_3,
    MAGE_PEA_CONSTANTS_4,
    MAGE_PEA_CONSTANTS_5,
    MAGE_PEA_CONSTANTS_6,
    MAGE_PEA_CONSTANTS_7,
    MAGE_PEA_CONSTANTS_8,
    MAGE_PEA_CONSTANTS_9,
    MAGE_PEA_CONSTANTS_10,
    MAGE_PEA_CONSTANTS_11,
    MAGE_PEA_CONSTANTS_12,
    MAGE_PEA_CONSTANTS_13,
    MAGE_PEA_CONSTANTS_14,
    MAGE_PEA_CONSTANTS_15,
    MAGE_PEA_RF_0,
    MAGE_PEA_RF_1,
    MAGE_PEA_RF_2,
    MAGE_PEA_RF_3,
    MAGE_PEA_RF_4,
    MAGE_PEA_RF_5,
    MAGE_PEA_RF_6,
    MAGE_PEA_RF_7,
    MAGE_PEA_RF_8,
    MAGE_PEA_RF_9,
    MAGE_PEA_RF_10,
    MAGE_PEA_RF_11,
    MAGE_PEA_RF_12,
    MAGE_PEA_RF_13,
    MAGE_PEA_RF_14,
    MAGE_PEA_RF_15,
    MAGE_AGE_IV_CONSTRAINTS_0,
    MAGE_AGE_IV_CONSTRAINTS_1
  } mage_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] MAGE_PERMIT[95] = '{
      4'b0001,  // index[ 0] MAGE_STATUS
      4'b0011,  // index[ 1] MAGE_GEN_CFG
      4'b1111,  // index[ 2] MAGE_ILB_HWL
      4'b1111,  // index[ 3] MAGE_FLB_HWL
      4'b1111,  // index[ 4] MAGE_INC_HWL
      4'b1111,  // index[ 5] MAGE_STRIDES_0
      4'b1111,  // index[ 6] MAGE_STRIDES_1
      4'b1111,  // index[ 7] MAGE_STRIDES_2
      4'b1111,  // index[ 8] MAGE_STRIDES_3
      4'b1111,  // index[ 9] MAGE_STRIDES_4
      4'b1111,  // index[10] MAGE_STRIDES_5
      4'b1111,  // index[11] MAGE_STRIDES_6
      4'b1111,  // index[12] MAGE_STRIDES_7
      4'b1111,  // index[13] MAGE_CFG_PE_00
      4'b1111,  // index[14] MAGE_CFG_PE_01
      4'b1111,  // index[15] MAGE_CFG_PE_02
      4'b1111,  // index[16] MAGE_CFG_PE_03
      4'b1111,  // index[17] MAGE_CFG_PE_10
      4'b1111,  // index[18] MAGE_CFG_PE_11
      4'b1111,  // index[19] MAGE_CFG_PE_12
      4'b1111,  // index[20] MAGE_CFG_PE_13
      4'b1111,  // index[21] MAGE_CFG_PE_20
      4'b1111,  // index[22] MAGE_CFG_PE_21
      4'b1111,  // index[23] MAGE_CFG_PE_22
      4'b1111,  // index[24] MAGE_CFG_PE_23
      4'b1111,  // index[25] MAGE_CFG_PE_30
      4'b1111,  // index[26] MAGE_CFG_PE_31
      4'b1111,  // index[27] MAGE_CFG_PE_32
      4'b1111,  // index[28] MAGE_CFG_PE_33
      4'b0001,  // index[29] MAGE_SEL_OUT_PEA_ROW_0_0
      4'b0001,  // index[30] MAGE_SEL_OUT_PEA_ROW_0_1
      4'b0001,  // index[31] MAGE_SEL_OUT_PEA_ROW_1_0
      4'b0001,  // index[32] MAGE_SEL_OUT_PEA_ROW_1_1
      4'b0001,  // index[33] MAGE_SEL_OUT_PEA_ROW_2_0
      4'b0001,  // index[34] MAGE_SEL_OUT_PEA_ROW_2_1
      4'b0001,  // index[35] MAGE_SEL_OUT_PEA_ROW_3_0
      4'b0001,  // index[36] MAGE_SEL_OUT_PEA_ROW_3_1
      4'b0001,  // index[37] MAGE_SEL_LOAD_STREAM_AGE_0_0
      4'b0001,  // index[38] MAGE_SEL_LOAD_STREAM_AGE_0_1
      4'b0001,  // index[39] MAGE_SEL_LOAD_STREAM_AGE_1_0
      4'b0001,  // index[40] MAGE_SEL_LOAD_STREAM_AGE_1_1
      4'b0001,  // index[41] MAGE_SEL_LOAD_STREAM_AGE_2_0
      4'b0001,  // index[42] MAGE_SEL_LOAD_STREAM_AGE_2_1
      4'b0001,  // index[43] MAGE_SEL_LOAD_STREAM_AGE_3_0
      4'b0001,  // index[44] MAGE_SEL_LOAD_STREAM_AGE_3_1
      4'b0001,  // index[45] MAGE_SEL_STORE_STREAM_AGE_0_0
      4'b0001,  // index[46] MAGE_SEL_STORE_STREAM_AGE_0_1
      4'b0001,  // index[47] MAGE_SEL_STORE_STREAM_AGE_1_0
      4'b0001,  // index[48] MAGE_SEL_STORE_STREAM_AGE_1_1
      4'b0001,  // index[49] MAGE_SEL_STORE_STREAM_AGE_2_0
      4'b0001,  // index[50] MAGE_SEL_STORE_STREAM_AGE_2_1
      4'b0001,  // index[51] MAGE_SEL_STORE_STREAM_AGE_3_0
      4'b0001,  // index[52] MAGE_SEL_STORE_STREAM_AGE_3_1
      4'b1111,  // index[53] MAGE_CFG_MAGE_S0_AGE0
      4'b1111,  // index[54] MAGE_CFG_MAGE_S0_AGE1
      4'b1111,  // index[55] MAGE_CFG_MAGE_S1_AGE0
      4'b1111,  // index[56] MAGE_CFG_MAGE_S1_AGE1
      4'b1111,  // index[57] MAGE_CFG_MAGE_S2_AGE0
      4'b1111,  // index[58] MAGE_CFG_MAGE_S2_AGE1
      4'b1111,  // index[59] MAGE_CFG_MAGE_S3_AGE0
      4'b1111,  // index[60] MAGE_CFG_MAGE_S3_AGE1
      4'b1111,  // index[61] MAGE_PEA_CONSTANTS_0
      4'b1111,  // index[62] MAGE_PEA_CONSTANTS_1
      4'b1111,  // index[63] MAGE_PEA_CONSTANTS_2
      4'b1111,  // index[64] MAGE_PEA_CONSTANTS_3
      4'b1111,  // index[65] MAGE_PEA_CONSTANTS_4
      4'b1111,  // index[66] MAGE_PEA_CONSTANTS_5
      4'b1111,  // index[67] MAGE_PEA_CONSTANTS_6
      4'b1111,  // index[68] MAGE_PEA_CONSTANTS_7
      4'b1111,  // index[69] MAGE_PEA_CONSTANTS_8
      4'b1111,  // index[70] MAGE_PEA_CONSTANTS_9
      4'b1111,  // index[71] MAGE_PEA_CONSTANTS_10
      4'b1111,  // index[72] MAGE_PEA_CONSTANTS_11
      4'b1111,  // index[73] MAGE_PEA_CONSTANTS_12
      4'b1111,  // index[74] MAGE_PEA_CONSTANTS_13
      4'b1111,  // index[75] MAGE_PEA_CONSTANTS_14
      4'b1111,  // index[76] MAGE_PEA_CONSTANTS_15
      4'b1111,  // index[77] MAGE_PEA_RF_0
      4'b1111,  // index[78] MAGE_PEA_RF_1
      4'b1111,  // index[79] MAGE_PEA_RF_2
      4'b1111,  // index[80] MAGE_PEA_RF_3
      4'b1111,  // index[81] MAGE_PEA_RF_4
      4'b1111,  // index[82] MAGE_PEA_RF_5
      4'b1111,  // index[83] MAGE_PEA_RF_6
      4'b1111,  // index[84] MAGE_PEA_RF_7
      4'b1111,  // index[85] MAGE_PEA_RF_8
      4'b1111,  // index[86] MAGE_PEA_RF_9
      4'b1111,  // index[87] MAGE_PEA_RF_10
      4'b1111,  // index[88] MAGE_PEA_RF_11
      4'b1111,  // index[89] MAGE_PEA_RF_12
      4'b1111,  // index[90] MAGE_PEA_RF_13
      4'b1111,  // index[91] MAGE_PEA_RF_14
      4'b1111,  // index[92] MAGE_PEA_RF_15
      4'b1111,  // index[93] MAGE_AGE_IV_CONSTRAINTS_0
      4'b1111  // index[94] MAGE_AGE_IV_CONSTRAINTS_1
  };

endpackage

